### ISSUE TITLE
[Idea] Object comprehension

### ISSUE THREAD

**Issue by ceymard** [satyr/coco#102]
I'm not sure I saw the way to do that, but since we have `array = (o for o of a)`, which is nice, could we also have something like `obj = (k: v for k, v in a)` ?

**Comment by satyr** [comment]
> could we also have something like `obj = (k: v for k, v in a)` ?

Changing the return value of the loop based on the last expressions isn't viable since they can be mixed:

```
x = for k, v in o
  if f k
    (k): v
  else
    v
```

For now the recommended way to achieve this is to use `new`:

```
obj = new
  @[k] = f v for k, v in o
```

**Comment by ceymard** [comment]
I'm not sure I understand this limitation...

Couldn't an exception be added to recognize a `label: value` construct before the `for` ?

**Comment by satyr** [comment]
> Couldn't an exception be added to recognize a `label: value` construct before the `for` ?

Like how exactly? Note that `x for k in o` is nothing more than a sugar for `for k in o then x`.

**Comment by ceymard** [comment]
Well then, couldn't we add a new kind of construct ?

`[f o, i for o, i of arr]` and `{ f k: f v for k, v of arr }`. I think that'd be fairly clear about what they do.

They would just do that : comprehension, not particularly sugar.

**Comment by satyr** [comment]
> `[f o, i for o, i of arr]` and `{ f k: f v for k, v of arr }`

Those are less {read,writ}able. How do you multiline them when the inner expressions aren't small?

> I think that'd be fairly clear about what they do

Not in Co{co,ffeeScript} context, where there are technically no _comprehensions_--only loops that returns array of last results.

**Comment by ceymard** [comment]
> Those are less {read,writ}able. How do you multiline them when the inner expressions aren't small?

If the expression isn't small, then it has nothing to do in a list/object comprehension ; it should be written like usual.

> Not in Co{co,ffeeScript} context, where there are technically no comprehensions--only loops that returns array of last results.

Which is why I propose we add a syntax specifically for comprehension. Maybe it's not a good Idea, but speaking of readability, I'm not sure I adhere 100% to the `new` alternative...

I guess it is all very subjective, but I kind of like the proposed syntax (which is python btw). I think the clarity comes from the fact that `[ ]` announces the creation of an array, while `{ }` that of an object.

The `( )` don't really announce anything (to me).

**Comment by satyr** [comment]
> If the expression isn't small, then it has nothing to do in a list/object comprehension ; it should be written like usual

Then I fail to see their values.

> I guess it is all very subjective, but I kind of like the proposed syntax (which is python btw). I think the clarity comes from the fact that `[ ]` announces the creation of an array, while `{ }` that of an object.

Emulating Python would do more harm than good at this point as our `for` works quite differently than Python's, e.g.:

```
$ python3
Python 3.2.2 (default, Oct  4 2011, 14:07:05) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> [x%y for x in [2,3] for y in [5,7]]
[2, 2, 3, 3]
>>> 

$ coco -i
coco> x%y for x of [2 3] for y of [5 7]
[ 2, 3, 2, 3 ]
```

> The `( )` don't really announce anything (to me).

Right, it's `for` that indicates array there. Parens are only for precedence aid, so you can do away with them:

```
array =
  o for o of a
```

**Comment by andrewrk** [comment]
Looks like LiveScript managed to pull this off: https://github.com/jashkenas/coffee-script/issues/77#issuecomment-6222959

**Comment by satyr** [comment]
Yep. By sacrificing post-`for`s, and without solving problems listed earlier here.
