### ISSUE TITLE
Feature: Allow `<-` in the REPL

### ISSUE THREAD

**Issue by thejh** [satyr/coco#104]
It would be awesome to be able to use `(err, data) <- fn foo` in the REPL - I usually write stuff like this to work around that:

```
fn foo, (err, data) -> global.err = err; global.data = data; console.log \done
```

Much longer, and uncool.

**Comment by satyr** [comment]
Multiline in general is a pain in the REPL. Have you tried <kbd>Ctrl-J</kbd>?

```
$ coco -bci
coco -cb> err, data <- fn foo
......... global <<< {err, data}
......... console.log \done
fn(foo, function(err, data){
  global.err = err;
  global.data = data;
  return console.log('done');
});
coco -cb> 
```

**Comment by thejh** [comment]
No, I didn't try that yet - but I think that it would be good to be able to
interactively do stuff with the callback results, too, which your solution
doesn't seem to be able to do. Do you think it'd be possible to kind of
move the repl context into the callback?

Am 15.11.2011 18:23 schrieb "Satoshi Murakami" <
reply@reply.github.com

> :

Multiline in general is a pain in the REPL. Have you tried
<kbd>Ctrl-J</kbd>?

```
$ coco -bci
coco -cb> err, data <- fn foo
......... global <<< {err, data}
......... console.log \done
fn(foo, function(err, data){
 global.err = err;
 global.data = data;
 return console.log('done');
});
coco -cb>
```

---

**Comment by satyr** [comment]
> Do you think it'd be possible to kind of move the repl context into the callback?

What behavior are you expecting, exactly? Is it something that node REPL is capable of?

**Comment by thejh** [comment]
I honestly have no idea whether it's easy or hard to do, and the node REPL doesn't support it out-of-the-box. But what I would like is the following:
- I enter `(err, data) <- foo!` into the REPL
- until `foo` calls back, the REPL prompt is gone
- when foo calls back, copy err and data in the current context or so and then show the prompt again
- I see that the prompt is back, so I know that the callback was fired
- I can do stuff with the callback parameters because they're in my scope now

**Comment by satyr** [comment]
I see. I'm skeptical about implementing a special behavior based on the presence of `<-`--certainly not easy/simple considering that `<- f; ...` is no different than `f -> ...` at AST level.

I'd rather just stick with your current approach which can be simplified a little:

```
coco> fs.writeFileSync \t \hello
undefined
coco> @err, @data <- fs.readFile \t; say \done
undefined
coco> done
[err, data]
[ null, <Buffer 68 65 6c 6c 6f> ]
coco> 
```

**Comment by thejh** [comment]
Hmm, right, guess I'm overcomplicating things. Closing.
