### ISSUE TITLE
` .` behaves different from ` ..`

### ISSUE THREAD

**Issue by thejh** [satyr/coco#105]
http://satyr.github.com/cup/#c:a%20b%20c%20.d%0Aa%20b%20c%20..d

Example 1:

```
a b c .d
a(b(c)).d;
```

Example 2:

```
a b c ..d
a(b(c(constructor.d)));
```

**Comment by satyr** [comment]
Expected behavior. `..` is identical to `constructor` and never has `.` semantics itself.

```
$ coco -bce ..
constructor;
```
