### ISSUE TITLE
Disallow double-underscore-leading variables

### ISSUE THREAD

**Issue by satyr** [satyr/coco#106]
To prevent conflict with the helper variables in the compilation.

(As in CoffeeScript, use of those variables has been tacitly forbidden but technically allowed.)

**Comment by ghost** [comment]
Something to consider is that this could still be circumvented via `eval`:

```
list = [1, 2, 3]
eval("__of = function() { console.log('Hijacked!'); };")
1 of list
```

**Comment by satyr** [comment]
Circumvention isn't a concern. You don't even need a `eval` because of JS literal: ``__of = null``

**Comment by ghost** [comment]
Ah, okay (I was referring to using `eval` if underscore-prefixed variables were disallowed). In that case, the only other concern is backward-compatibility, though I doubt prefixed variables are as common in Coco and CoffeeScript as they are in JS.

**Comment by ceymard** [comment]
Are you sure about doing such a change ?

I do use leading `_` to indicate that the variable is more of a "private" nature than another.

**Comment by satyr** [comment]
> I do use leading `_` to indicate that the variable is more of a "private" nature than another.

Was anticipating that's already the case. Doing so is highly dangerous and discouraged due to the _readable_ naming of internal temporaries.

Other options to avoid the collisions are:
- Never use the same name as user variables for temporaries.
  - Costly due to additional scanning and matching.
  - Related: #100
- Make the naming of temporaries more consistent (e.g. prefix `__` to all) and disallow only those.
- ?

**Comment by mcfog** [comment]
I think name the helpers with __coco_xxxx (and maybe disallow __coco_var) is a better idea

underscore-leading variable suggest "private thing" is a python convention and it's good in javascript too.

also you can find _vars in jQuery or Dojo or many other js libs,

**Comment by satyr** [comment]
> I think name the helpers with __coco_xxxx (and maybe disallow __coco_var) is a better idea

Long prefix hurts readability. `__` is about as far as we can tolerate.

**Comment by ceymard** [comment]
Generated code is not really meant to be read directly by the programmer, and it would be nice when debugging to instantly see which variables were added by coco (instead of wondering if you did that yourself :) )

**Comment by satyr** [comment]
> Generated code is not really meant to be read directly by the programmer

Generally yes, but CoffeeScript/Coco is different in this regard. The readability of the compilation is a major goal and plays an important role for its adoption.

> it would be nice when debugging to instantly see which variables were added by coco

Right. Double underscores would be good enough for that.

**Comment by thejh** [comment]
Maybe you could just use some other prefix? Stuff that comes to my mind:
- random prefix, different for each compiled file
- weird unicode prefix, examples: `ω`, `Δ`, `δ` (yes, those are valid identifiers)

Alternatively, we could use `$coco_` or so - [the EcmaScript spec](http://bclary.com/2004/11/07/#a-7.6) says:

> The dollar sign is intended for use only in mechanically generated code.

**Comment by satyr** [comment]
> [the EcmaScript spec](http://bclary.com/2004/11/07/#a-7.6) says:
> 
> > The dollar sign is intended for use only in mechanically generated code.

That's pre-jQuery. Nowadays it's common to see code like:

```
$div = $('div')
```

**Comment by thejh** [comment]
hehe

**Comment by thejh** [comment]
So, how about weird unicode?

**Comment by satyr** [comment]
> So, how about weird unicode?

Too fancy. Sticking to ASCII range avoids potential encoding issues.

**Comment by satyr** [comment]
Title edited. (was: Disallow underscore-leading variables except `_` itself)

**Comment by satyr** [comment]
I guess those commits are enough to keep accidental conflicts for now. We'll just avoid `__xxx` instead of `_xxx`. Disallowing all `__xxx` isn't viable even considering Node only (`__filename` and `__dirname`).
