### ISSUE TITLE
Sometimes asterisk gets dropped

### ISSUE THREAD

**Issue by thejh** [satyr/coco#107]
Looks like a bug to me:

```
a
*b
```

compiles to

```
a;
b;
```

Also:

```
*b
```

compiles to

```
b;
```

Lexer produces:

```
NEWLINE:\n { } ASSIGN:= INDENT:1 ID:b DEDENT:1 NEWLINE:\n
```

However, this works:

```
a*
b
```

I think that part of the problem is in the lexer https://github.com/satyr/coco/blob/master/src/lexer.co#L318-321 because it doesn't check the first char of the current line, only the last one of the previous line, but that's probably not everything.

**Comment by satyr** [comment]
Leading `*` is used for listing.

```
$ coco -bcs
  * a
  * b
    c

a;
[b, c];
```

> I think that part of the problem is in the lexer https://github.com/satyr/coco/blob/master/src/lexer.co#L318-321 because it doesn't check the first char of the current line, only the last one of the previous line, but that's probably not everything.

This check is only for dangling cases. The next token isn't lexed yet and can't reliably be checked here.
