### ISSUE TITLE
Variable name reuse with loops and let

### ISSUE THREAD

**Issue by jdknezek** [satyr/coco#108]
I see `let` has some edge cases when used with a loop variable:

```
$ coco -bce 'let a = a + 1 then'
(function(a){}.call(this, a + 1));

$ coco -bcs
for a in b
  let c = c + 1 then

var a;
for (a in b) {
  (_fn.call(this, c + 1, a));
}
function _fn(c, a){}
```

Notice that coco is being nice and capturing `a` for me.  However, this means I can't define my own new `a`:

```
$ coco -bcs
for a in b
  let a = a + 1 then

SyntaxError: duplicate parameter "a" on line undefined
```

It would be nice if coco would let me override the automatic capture:

```
$ coco -bcs
for a in b
  let a = a + 1 then

var a;
for (a in b) {
  (_fn.call(this, a + 1));
}
function _fn(a){}
```

**Comment by satyr** [comment]
I'd write that as:

```
for a in b
  let then a += 1
```

Though yes, it should avoid duplicating the parameter.

**Comment by jdknezek** [comment]
That's what I ended up doing.  I was actually writing up the issue completely differently until I realized that `a` was being captured automatically!  Does an empty `let` capture all local variables?  If so then it's almost a non-issue, it should just probably be documented.  Neither of the examples on [additions](https://github.com/satyr/coco/wiki/additions) demonstrate that.

**Comment by satyr** [comment]
> Neither of the examples on [additions](https://github.com/satyr/coco/wiki/additions) demonstrate that.

**loop** → **scoped**

**Comment by jdknezek** [comment]
Yep, perfect.  I started from [incompatibilities](https://github.com/satyr/coco/wiki/incompatibilities) with CS's `do`, which directed me to `let`, and the first [additions](https://github.com/satyr/coco/wiki/additions) example showed what I thought would work, `let c, @d`.  I gave up too soon, sorry!
