### ISSUE TITLE
Nested list comprehensions order

### ISSUE THREAD

**Issue by gkz** [satyr/coco#109]
First of all, great work on Coco!  List comprehensions are flat as they should be. The order in which they are constructed however is different from how it is regularly done in other languages - this seems to be an artifact from Coco's CoffeeScript ancestry. The `for` the furthest to the right should be the fastest. 

e.g.
It is translating 

```
"#x#y" for x of [1, 2, 3] for y of ['a', 'b', 'c']
```

as

```
for y of ['a', 'b', 'c']
    for x of [1, 2, 3]
        "#x#y"
```

instead of the expected:

```
for x of [1, 2, 3]
    for y of ['a', 'b', 'c']
        "#x#y"
```

---

An example:

In **Coco**:

```
"#x#y" for x of [1, 2, 3] for y of ['a', 'b', 'c']
```

is 

```
1a,2a,3a,1b,2b,3b,1c,2c,3c
```

While in **Python**

```
["{0}{1}".format(x, y) for x in [1, 2, 3] for y in ['a', 'b', 'c']]
```

is 

```
['1a', '1b', '1c', '2a', '2b', '2c', '3a', '3b', '3c']
```

and in **Haskell**

```
[(show x) ++ y | x <- [1,2,3], y <- ["a","b","c"]]
```

is 

```
["1a","1b","1c","2a","2b","2c","3a","3b","3c"]
```

**Comment by satyr** [comment]
Although the flattening issue is fixed, the basic concept remains the same: rather than providing a dedicated syntax for list comprehension, Coco/CoffeeScript simply lets its loops return the collection of last values.

The confusing factor wrt Python/Haskell syntax is that the loop constructions has postfix forms, e.g.:

```
x for x of xs
# ↓↑
for x of xs
  x
```

which is naturally _left_-associative, so the rightmost corresponds to the outermost:

```
x+y for x of xs for y of ys
# ↓↑
for y of ys
  for x of xs
    x+y
```

Perl6 list-comprehends similarly to us:

```
$ perl6
> $_ if $_%2 for 1..5
1 3 5
> for 1..5 -> $i { if ($i%2) { $i } }
1 3 5

$ coco -i
coco> i if i%2 for i from 1 to 5
[ 1, 3, 5 ]
coco> for i from 1 to 5 then if i%2 then i
[ 1, 3, 5 ]
```

**Comment by gkz** [comment]
Ah yes, I understand the causes, but somehow thought that you were treating for loops differently already due to the flattening of the results and that this would just be an addition to that special treatment, but I see I was wrong. 

Have you considered adding a dedicated comprehension syntax?

edit:
see https://github.com/jashkenas/coffee-script/issues/77#issuecomment-3674695

**Comment by satyr** [comment]
> Have you considered adding a dedicated comprehension syntax?

Nope. That would complicate the situation further.
