### ISSUE TITLE
Feature: Specify own function for joining parts of string interpolation

### ISSUE THREAD

**Issue by thejh** [satyr/coco#113]
Hello,

I've been thinking about porting https://github.com/jashkenas/coffee-script/pull/2050 to coco, which requires changes like this one all over the nodes code:

``` diff
- "#res.push"
+ @s res, '.push'
```

And this is one of the not-so-bad examples. Maybe it'd be possible to create a new syntax for this? Ideas:

```
"#res.push" with @s
"#res.push" @s
```

Basically, this would transform into a call with an array containing the parts of the string interpolation as last argument.

On the other hand, this is pretty special-case and not exactly good-looking either. What do you think?

**Comment by satyr** [comment]
Interesting. We could specify some prefix that makes the result an array. E.g.:

`&"#res.push"` => `[res, ".push"]`

Then you can:

```
@s ...&"#res.push"
```

**Comment by thejh** [comment]
Sounds good. :)

**Comment by satyr** [comment]
So which sigil makes sense the most?
- `&`
- `|`
- `%`

**Comment by thejh** [comment]
Maybe `|` or `%` for "seperation"? `%` seems very clear to me, "seperated elements", it's not used very often and it's relatively big.

**Comment by satyr** [comment]
> `%` seems very clear to me, "seperated elements"

Good point. Will try implementing with that shortly.

**Comment by thejh** [comment]
Cool :)

**Comment by vendethiel** [comment]
Sorry to bring this up after 6 months, but I think this should be documented somewhere.

**Comment by satyr** [comment]
https://github.com/satyr/coco/wiki/additions/_compare/a8c9b0e964a187a114cd6bea1e9b91192f488eca...8a17309b796fa3c8f6a447926f514c69474b8166
