### ISSUE TITLE
extras/coco.js bug, license year

### ISSUE THREAD

**Issue by gkz** [satyr/coco#114]
Hi,
I already have a fork of Coco so it doesn't look like I can nicely make another one through the github interface to make easy pull requests - so here are some minor things I've noticed.

In the Cokefile, line 102 needs `//` prepended making it a JavaScript comment. At first I was puzzled as to how it was working currently without any JS errors, but I think what is happening is that everything after the `http:` is ignored as it is a comment (http:**//**), and the `http:` is being interpreted as a label, doing nothing. 

While you're there you could change the year in the copyright to 2012, and also in the license file if you want, but that's really minor.

**Comment by satyr** [comment]
> I think what is happening is that everything after the `http:` is ignored as it is a comment (http:**//**), and the `http:` is being interpreted as a label, doing nothing. 

Exactly. It's an intentional prank.

> you could change the year in the copyright to 2012, and also in the license file if you want

Will do.
