### ISSUE TITLE
Feature: "function exports.name"

### ISSUE THREAD

**Issue by apaleslimghost** [satyr/coco#116]
Would be sugar for `exports.name = name = function name`, just as with class.

**Comment by satyr** [comment]
Would require large changes in lexer/grammar.

Instead maybe we can add `export` keyword:

```
export function name then
```

compiling to:

```
var __out = typeof exports != 'undefined' && exports || this;
__out.name = name;
function name(){}
```

**Comment by apaleslimghost** [comment]
I realise it's just wishful thinking at this point, but the same or similar grammar would allow `function @name` for class functions.

**Comment by satyr** [comment]
`@name = function then ...` should do in that case.

**Comment by apaleslimghost** [comment]
Ah, didn't realise that would keep the name on the function, which also works for `exports.name` and was basically the point of this issue. I'm closing it.
