### ISSUE TITLE
no --join

### ISSUE THREAD

**Issue by ghost** [satyr/coco#117]
Coco does not have a --join option?

**Comment by satyr** [comment]
Nope. Use your command-line-fu and/or favorite build tools.

**Comment by ghost** [comment]
With all due respect, coco is a command line program. :P

**Comment by scribu** [comment]
The beauty of UNIX CLI programs is that they are composable, i.e. the `--join` parameter doesn't need to be implemented for each program. You use `>>` to append to a file etc.

**Comment by satyr** [comment]
Exactly.

`coffee -cj ab.js a.coffee b.coffee`

is identical to:

`cat a.coffee b.coffee | coffee -sco ab.js`

Note that this approach is hardly recommended. `--join`ed scripts share the same variable scope, cancelling the merit of separating files in the first place.
