### ISSUE TITLE
Idea: enable "void function"

### ISSUE THREAD

**Issue by ghost** [satyr/coco#118]
It'd be nice to be able to type "void function" instead of "!function".

**Comment by satyr** [comment]
Anyone wanting this as well?

I thought about this once on implementing #91, but it seemed unnecessary. If you want to be verbose, you can still write out:

```
function f
  ...
  void
```

or even

```
not function f  # not a function, but a subroutine of sort
  ...
```

**Comment by ghost** [comment]
Maybe you could do:

```
routine s
 ...
```

??
Maybe event instead of routine.
