### ISSUE TITLE
Iterators result in excess JavaScript.

### ISSUE THREAD

**Issue by ghost** [satyr/coco#119]
``` coffeescript
total_cost_me = 0; (total_cost_me += x.cost for x of responce_units)
  /* check the total cost to build all of the units. */
```

Results in:

``` javascript
    total_cost_me = 0;
    (function(){
      var _i, _ref, _len, _results = [];
      for (_i = 0, _len = (_ref = responce_units).length; _i < _len; ++_i) {
        x = _ref[_i];
        _results.push(total_cost_me += x.cost);
      }
      return _results;
    }());
```

This could be make cleaner by not concatenating the results into an array which is discarded immediately afterwards, and not calling a function (since we don't need the result.)

**Comment by satyr** [comment]
The parens force the _results_ compilation. What's wrong with

```
total_cost_me = 0
total_cost_me += x.cost for x of response_units
// check the total cost to build all of the units.
```

?

**Comment by ghost** [comment]
Maybe you could make it check if the return value is used? I have changed it, but it can randomly add junk code, so I still think it's a bug.

**Comment by satyr** [comment]
> Maybe you could make it check if the return value is used?

To what extent?

```
f = ->
r = (x for x of xs)
f r
```

Should the compiler eliminate all of those since they accomplish nothing?

**Comment by ghost** [comment]
My thoughts would be to check if an expression is used only. Not to bother with functions, because it would be too complicated.

For example, "(x for x of xs)" should return results because it is assigned.
But, not to return results for things which aren't used.
