### ISSUE TITLE
"is not" is rather strange

### ISSUE THREAD

**Issue by ghost** [satyr/coco#120]
Using "is not" instead of "isnt" doesn't make sense to me.

If I do:

```
a is not b
```

I expect:

```
a === !b
```

Rather than:

```
a !== b
```

I think isnt should be used instead to keep it clearer and less ambiguous.

**Comment by satyr** [comment]
It's a compound keyword. `for own` is another.

**Comment by ghost** [comment]
@camellia0x I actually think the distinction between `isnt` and `is not` is one of CoffeeScript's more esoteric features. The problem is that the compilation isn't intuitive at all...`!b` will always return a boolean (`true` or `false`), and, since `===` is used, `a` can _only_ be a boolean for the expression to return anything meaningful (otherwise, it'll always be `false`).

That said, you can write `a is !b` to obtain `a === !b`.

**Edit**: Or even `a is (not b)`, if you'd prefer to avoid the `!` symbol.

**Comment by ghost** [comment]
I'm not suggesting that I'm not able to do a is !b, but rather that I think "is not" looks strange, and that it seems to be using a "compound keyword" for no real reason.

**Comment by satyr** [comment]
The _real_ reasons are to:
- reserve one less keyword.
- follow the lead of Python.

**Comment by ghost** [comment]
W/e, it isn't super important, just annoying to me.

**Comment by andreypopp** [comment]
For the record "is not" also works in Python — "something is not None", same for "not in" — "1 not in (2, 3)"
