### ISSUE TITLE
Bug: a {arguments}

### ISSUE THREAD

**Issue by ghost** [satyr/coco#123]
if you type:

```
function f
 a {arguments}
```

You get a compile error.

```
function f
 a {arguments: arguments}
```

Works fine.

**Comment by satyr** [comment]
1. `arguments` is a special, immutable variable as per ES5 strict, so Coco treats it just like other keyword literals.
2. Keyword literals can't be used for object shorthand. `{this}`, `{true}` etc. also don't work.

Allowing 2. is technically possible though.

**Comment by ghost** [comment]
I don't think an immutable variable should be treated like a keyword.
I can use `sudo chattr +i file` to make a file immutable, but I can still use it like any other file, except that I can't modify it. `{arguments}` does not modify the array.

**Comment by satyr** [comment]
Immutability itself isn't relevant here. Just that `arguments` is _LITERAL_ in our grammar for convenience (as it's more like `this` than a normal variable in ES5 strict), and there's no rule for "{ LITERAL }" to parse.

I guess I'll shut you up by allowing them.

**Comment by ghost** [comment]
No need...
