### ISSUE TITLE
Generating functions in a loop

### ISSUE THREAD

**Issue by n9** [satyr/coco#126]
Is this a bug?

http://stackoverflow.com/questions/10191806/how-to-generate-functions-in-a-loop-in-coco

It seems that coffeescript generates the javascript as intended.

**Comment by satyr** [comment]
I'll answer there.

**Comment by ghost** [comment]
I think this is a nonsensical change from coffeescript.

**Comment by n9** [comment]
Thx for the answer.

**Comment by satyr** [comment]
> I think this is a nonsensical change from coffeescript.

Coffee partially implements this too:

```
$ coffee -bce 'for k of o then do ->'
// Generated by CoffeeScript 1.3.1
var k, _fn;

_fn = function() {};
for (k in o) {
  _fn();
}
```
