### ISSUE TITLE
Suggestion: Make export compatible with ADVANCED_OPTIMISATIONS using closure compiler.

### ISSUE THREAD

**Issue by ghost** [satyr/coco#128]
The suggestion to to use `__out['f'] = bla` instead of `__out.f = bla`. The reason is that the closure compiler differentiates between the two. It treats `a.foo` more like a static object, and optimises (renames and etc) `a.foo`, while it does not optimise `a['foo']`.
When saving JSON to files, it is desirable for it not to rename the property, as different versions of the script may create different names for the same property.  

Second suggestion (if the first is rejected), is possibly to allow `export function \blabla` which would make it use the above syntax instead.

**Comment by satyr** [comment]
Optimizing for every other build tool isn't viable, especially if it'd lead to uglier compilations.

I guess simple mid-processing should be sufficient in this particular case:

```
$ coco -bce 'export a' | perl -pe 's/^( *__out)\.([\$\w]+)/$1\["$2"]/'
var __out = typeof exports != 'undefined' && exports || this;
__out["a"] = a;
```
