### ISSUE TITLE
a void void compiles to a(void 8, void 8)

### ISSUE THREAD

**Issue by ghost** [satyr/coco#129]
`a void void` compiles to `a(void 8, void 8)`. Is this supposed to happen?

**Comment by satyr** [comment]
Yep. What compilation do you expect?

**Comment by ghost** [comment]
More like, `a(void 8)(void 8)` was what I expected...

**Comment by satyr** [comment]
Ah, but Coco isn't Haskell.
- `void void` is short for `void, void` due to ACI (automatic comma insertion).
- `a void, void` is short for `a(void, void)` due to implicit call.

**Comment by ghost** [comment]
Why exactly is automatic comma insertion needed?

**Comment by satyr** [comment]
For simpler notations. `[1 2 3]` is less redundant than `[1, 2, 3]`.
