### ISSUE TITLE
Class inheritance doesn't inherit constructors

### ISSUE THREAD

**Issue by andreypopp** [satyr/coco#130]
```
# test.co
class A
  msg: 'A'
  ->
    console.log(this.msg)

class B extends A
  msg: 'B'

a = new A
b = new B
```

and then `coco test.co` gives:

```
A
```

while I expect

```
A
B
```

Corresponding CoffeeScript test case behaves as expected, does it somehow assumed to be the proper way of implementing inheritance of am I hitting a bug?

**Comment by satyr** [comment]
Coco removed the implicit `super` call on constructor omission. Try:

```
class B extends A
  -> super ...
  ...
```

**Comment by andreypopp** [comment]
Wow, didn't find that in incompatibilities section, any insights why it was done?

**Comment by satyr** [comment]
> didn't find that in incompatibilities section

The current CoffeeScript's `class` is [based on Coco's](https://github.com/jashkenas/coffee-script/issues/841). So technically this isn't _our_ change from CoffeeScript. ;)

> any insights why it was done?

Omission meaning an empty constructor regardless of `extends` is easier to remember/understand. It's awkward to have to write a dummy `->` when the `super` call isn't needed.

**Comment by andreypopp** [comment]
> The current CoffeeScript's class is based on Coco's. So technically this isn't our change from CoffeeScript. ;)

Well, ok :-)

> Omission meaning an empty constructor regardless of extends is easier to remember/understand.

I disagree here, first of all, all methods are inherited by default so why constructor should be a special case? Second, it also violates Liskov substitution principle which is essential in OO programming. Probably you want to keep things close to JS semantics, but class system is kinda orthogonal to what we can found in JS — prototype chains, so if you want to ressemble class-based OO systems it's mandatory (as I think) to also inherit constructors.

**Comment by satyr** [comment]
> all methods are inherited by default so why constructor should be a special case?

We don't pretend that `constructor` is a method. It simply isn't in JS.

> you want to keep things close to JS semantics

Exactly. Likewise we don't emulate class methods.

**Comment by andreypopp** [comment]
The point was — class system can't be kept close to JS semantics because it isn't JS thing at all, but I understand your point like it is done by design so closing this issue.

**Comment by andreypopp** [comment]
Just not to create another issue — are static class attributes not inherited by design also?

**Comment by satyr** [comment]
Yes.
- You can't actually inherit them without the non-standard `__proto__` injection.
- Copying as pseudo inheritance is a leaky abstraction.
