### ISSUE TITLE
else binds to wrong if

### ISSUE THREAD

**Issue by goto-bus-stop** [satyr/coco#131]
```
if b then if c then d else e
```

compiles to

```
if (b) {
  if (c) {
    d;
  }
} else {
  e;
}
```

and

```
switch a
case b then if c then d else e
```

fails.

In the first case, I'd expect the else to bind to the innermost if, 

```
if (b) {
  if (c) {
    d;
  } else {
    e;
  }
}
```

And it's quite the same with the switch case, except of course that a `case` doesn't take an `else` and therefore fails to compile.
It kind of dedents implicit blocks (too?) enthusiastically:
`if a then if c then b else e`
=>
`IF ID:a INDENT:0 IF ID:c INDENT:0 ID:b DEDENT:0 DEDENT:0 ELSE INDENT:0 ID:e DEDENT:0 NEWLINE:\n`

**Comment by satyr** [comment]
See #127. This is an inherent defect of CoffeeScript's `then`.

**Comment by goto-bus-stop** [comment]
Woops, I actually read through that issue before but, apparently, forgot...
