### ISSUE TITLE
Irregularity in star syntax for arrays

### ISSUE THREAD

**Issue by redalastor** [satyr/coco#132]
If I write:

```
foo =
    * \one
    * \two
```

It gets translated as: `foo = ['one', 'two']` (as it should)

But if I write:

```
bar =
    * \one
```

I get `bar = 'one'`.

Is that the expected behaviour? What's the rationale?

**Comment by satyr** [comment]
Implicit array needs two or more items to take effect.

```
$ coco -ps
  foo =
    \one
    \two

  bar =
    \one

  [foo, bar]

[ [ 'one', 'two' ], 'one' ]
```

Same for the leading `*`, which is merely a short for an empty assignment with block. E.g.:

```
bar =
  * \one
```

is equivalent to:

```
bar =
  void =
    \one
```

Also see #63.
