### ISSUE TITLE
Improve CLI / REPL

### ISSUE THREAD

**Issue by josher19** [satyr/coco#134]
Hi satyr, Thought this might interest you.
Cross posting from https://github.com/gkz/LiveScript/issues/12

If you start a line with `[` in the CLI/REPL, coffee throws a long error message.
livescript and coco throw a nicer error message: `SyntaxError: missing ] on line 1.`
node indents and prompts you for more array input.

I prefer node's solution. It would be great if that would also work for function definitions as well, so:

```
g = (a,b) ->
  a + b
```

would work without needing ^J (or \ in CoffeeScript).

Of course, this could make the CLI client slightly more complex, but I'd much prefer 
to have the CLI automatically indent my next line for me and wait for more input
when I enter

`coco> g = (a,b) ->`

instead of the no-op function:

``` javascript
[Function]
function (a, b){}
```

which is what I'd expect from g = (a,b) -> followed by two newlines.

From: https://github.com/gkz/LiveScript/issues/12
(have a partial solution posted there, but something more like node's solution would be better).

Possibly related:
https://github.com/satyr/coco/issues/104

**Comment by satyr** [comment]
My preferred solution is to use tools better suited for large/multiline input (such as [cup](http://satyr.github.com/cup/), [xqjs](https://addons.mozilla.org/firefox/addon/xqjs), and [`CocoRun` on Vim](https://github.com/satyr/vim-coco)). A few more lines for a little convenience doesn't hurt though.

> a partial solution
> 
> > Dangling =, ->, ~>, [, or { at the end of the line will read input until a blank line is found.

Auto-continuation on certain line end is viable, but only for simple cases. Correctly detecting e.g.:

```
coco> a = "
```

will be nightmare via regexes; you'd need to implement a compiler hook for partial-but-valid parses.

> something more like node's solution

`node`'s solution is actually pretty bald--continue on a `SyntaxError`--thus prone to stupid behaviors like:

```
> a = ;
...
```
