### ISSUE TITLE
`__` prefix to `$` suffix

### ISSUE THREAD

**Issue by satyr** [satyr/coco#136]
Suggested by @bga.

```
var x, __i, __ref, __len;
for (__i = 0, __len = (__ref = xs).length; __i < __len; ++__i) {
  x = __ref[__i];
}
```

↓

```
var x, i$, ref$, len$;
for (i$ = 0, len$ = (ref$ = xs).length; i$ < len$; ++i$) {
  x = ref$[i$];
}
```

Reads better? Pointless?

**Comment by mikeaustin** [comment]
Bindings prefixed with __ is pretty synonymous with "reserved for the compiler".  Is the purpose to make the generated code clearer when debugging?

**Comment by satyr** [comment]
Yup, it's all about readability.

**Comment by markmarijnissen** [comment]
Reads absolutely worse!

The "__" has lot's of white space, which makes it easy to detect with the eye. For me, it's a clue I can ignore it -- it's just to help the actual code I wrote.

"$" takes up just as much space as a normal character (even a little bit more), which makes the code look chaotic. Also, I find a suffix less easier to detect than a prefix.

The result is that I find it harder to fish out "my code" from "compiler code". 

Judge for yourself:

```
var res$, key, ref$, val, r;
res$ = {};
for (key in ref$ = {
  a: 1,
  b: 2
}) {
  val = ref$[key];
  res$[key] = val * 2;
}
r = res$;
```

-vs-

```
var __res, key, __ref, val, r;
__res = {};
for (key in __ref = {
  a: 1,
  b: 2
}) {
  val = __ref[key];
  __res[key] = val * 2;
}
r = __res;
```

especially in arrays, it's just weird to have the $ between the variable name and the brackets.
`$var[a]` and `__var[a]` -vs- `var$[a]`. You judge yourself.

**Comment by michaelficarra** [comment]
@markmarijnissen: I like it and have adopted a similar naming scheme for generated symbols in my own compiler. To each his own.

**Comment by vendethiel** [comment]
My eyes aren't reading the "$", and I feel the difference when I'm looking at compiled code
