### ISSUE TITLE
equivalent of coffeescript eval?

### ISSUE THREAD

**Issue by justinfreitag-zz** [satyr/coco#140]
Not sure if you left it out for a reason, but the gist below is a coco'd version.

https://gist.github.com/2957964

**Comment by satyr** [comment]
We don't provide one because JS evaluation can take various forms:
- `eval`
- `Functinon`
- `setTimeout`
- `<script>`
- `vm.runInContext`
- `Services.scriptloader.loadSubScript` + data URL
- ...

Coco is a transpiler, not an interpreter.
