### ISSUE TITLE
Instanceof and that

### ISSUE THREAD

**Issue by apaleslimghost** [satyr/coco#148]
`instanceof` has higher precedence than assignment, but `if a instanceof b then that` compiles to `if(that = a instanceof b) {that;}`. In my mind, I'd prefer `that` to point to `a`, rather than the result of the `instanceof`. Is the current compilation correct behaviour?

Edit: to me, it should be consistent with the existing `if a? then that` → `if((that = a) != null){that;}`.

**Comment by satyr** [comment]
Postfix-`?` is currently the only specialcase for `that` because:
- being unary, its target is obvious.
  (Not so much for binary ops. `(that = a) of b` or `a of (that = b)`?)
- it has traditionally been the indicator of special syntaxes, e.g.: `a? b`, `a? = b`
