### ISSUE TITLE
filename with dots (e.g. jquery.plugin.co) compiles to file without .js extension

### ISSUE THREAD

**Issue by jedilando** [satyr/coco#155]
Version 0.7.6, Windows XP

examples

> coco -c jquery.plugin.co

creates jquery.plugin

> coco -c a.b.c.d.co

creates a.b.c.d

> coco -c a.co

creates a.js

**Comment by satyr** [comment]
This is intentional. To support non-`.js` targets, `.js` isn't added when the source has multiple extensions (`foo.jsm.co` → `foo.jsm`).

In this case use `jquery.plugin.js.co`.

**Comment by jedilando** [comment]
Ok, thank you!
