### ISSUE TITLE
Treat "volatile" as a special key

### ISSUE THREAD

**Issue by vendethiel** [satyr/coco#156]
Hi,

In order to make Closure Compiler happy, the "volatile" has to be quoted like 'class'.
audreyt/ethercalc/07afabd4a3346e2a980128cdde4bce7b243ecf7e

**Comment by satyr** [comment]
- We don't support ES3 future reserved words as they practically don't matter.
  - [JScript doesn't reserve them all](http://download.microsoft.com/download/8/4/2/8427CF1B-08B3-4557-952D-102E7A8FA64C/%5BMS-ES3%5D.pdf).
  - Non-JScript old engines are pretty much extinct today. 
- Closure compiler has ES5 mode. You should be able to specify `--language_in=ES5` or even `--language_in=ES5_STRICT`.
