### ISSUE TITLE
Hyphenated names for functions

### ISSUE THREAD

**Issue by ayatkevich** [satyr/coco#162]
### Last char of the hyphenated name for the function will be used as first argument

For example:
`function hyphenated-name then void`
Compiles to:
`function hyphenatedName(e){}`
### Hyphenated name for the function can not be used with arguments

Example:
`function hyphenated-name arg then void`
Raises:
`SyntaxError: invalid assign on line 1`

**Comment by satyr** [comment]
Ow. Fixing shortly.

**Comment by vendethiel** [comment]
LINK gkz/livescript#143
