### ISSUE TITLE
let for

### ISSUE THREAD

**Issue by vendethiel** [satyr/coco#164]
jashkenas/coffee-script#2518

`let for` looks right to me, or `for let`

**Comment by satyr** [comment]
`for let` maybe.

**Comment by vendethiel** [comment]
Yes, `for let` sounds more correct syntax-wise - `let for` sounds more "english like" - but I know you believe english, or any natural language, is total crap. But I feel like it "adds" to the for syntax, without need.

**Comment by vendethiel** [comment]
Any +1/-1 ? I think it's a regular use case (please `let for`).

**Comment by satyr** [comment]
FWIW, ES6 version will look like: `for (let x of xs)`

**Comment by vendethiel** [comment]
I doesn't matter much, both syntaxes are ok. True with the parenthesis it looks as nice, without a bit less - but I'd still be as happy.

**Comment by satyr** [comment]
#### More analysis

We already got idioms using `let` and `for` together:
1. `let`+`for`: Localizing the loop variables
   
   ```
   let
     for x, i of xs
       ...
   ```
2. `for`+`let`: Creating fresh bindings for each iteration
   
   ```
    for x, i of xs
     let
       ...
   ```
- The proposal may need to do both **1** and **2** efficiently to be worth a new construction.
- `let for` as proposed is clearly confusing due to **1**.
  - `for let` it is.
    - `for let own` or `for own let`, or both?

**Comment by vendethiel** [comment]
This does not work :

``` coffeescript
for [x,y,z] of b
  let
    x + y + z
```

For let would capture any loop variable, even the destructurations
`let own`/`own let` it depends if the `own` is seen as a for construct or applicated to the variable, I suppose.

**Comment by satyr** [comment]
> This does not work

Nope, because auto-binding all of them is costly and may not be desirable (and you can always do `for b => let [x, y, z] = & => ...`).

> depends if the `own` is seen as a for construct or applicated to the variable, I suppose

Both, I suppose.

**Comment by vendethiel** [comment]
That's what the suggestion is for. Capture them. Maybe you can consider searching them in the block, like that/if. May be costly too, but not at runtime.

**Comment by satyr** [comment]
> Capture them

Naturally it will, since it won't have to expose the bindings to the outer scope as well.

```
for let bindings, i of xs => ...
```

will compile roughly as:

```
for tmp, tmp-i of xs
  let bindings = tmp, i = tmp-i
    ...
```

**Comment by vendethiel** [comment]
Which is what we're looking for, isn't it ?

**Comment by vendethiel** [comment]
Okay, I have something.
It's super ugly, super unoptimized etc etc. I wanted to use `Call.let` but I didn't managed to make it work :(.
d3223ce5e0d34c2966aefef2972b3473e53fe6dd, cleaned up (a **tiny** bit) (allowing `let for a, b of c then`) by 44a0c906634970cc85d2f78aa433a76abb81c95c
Should work with `makeReturn`.

It got over my head really fast, I guess I need far more experience haha

**Comment by vendethiel** [comment]
[My diff is here](https://github.com/Nami-Doc/coco/compare/7915ca548825f89232de3629d098f87251bff7b4...b4dec643885d560ad77948180c13de76c525422f). (still a `@idx =` left)
That's still pretty bad as I have basically no idea how coco works, but at least I don't feel so much shame when reading it.
It currently messes up the indentation, tho.

``` js
$ node lib/command -bce "let for a in b then"
var a;
for (a in b) {
(fn$.call(this, a))
}
function fn$(a){}
```
- Not indented
- Misses the `;`
  is it because of `LEVEL_TOP`?

**Comment by satyr** [comment]
- Make it `for let` as decided above.
- You need to build the `let` structure beforehand for non-cross-scope traversings (the normal mode of `traverseChildren`) from parent nodes.

> - Not indented
> - Misses the `;` is it because of LEVEL_TOP?

`@body` is expected to be a _Block_.

**Comment by vendethiel** [comment]
> - Make it for let as decided above.

Cleanest way I think of, to avoid messing with LoopHeads, would be to invert tokens in the lexer. Or is there anything else ?

> - You need to build the let structure beforehand for non-cross-scope traversings (the normal mode of traverseChildren) from parent nodes.

When is that ? In `makeLet` (`(@let = true) -> this` would be better) ?
I don't see how I can do that, I don't have access to `svar`/`idx`.
Or before calling `While.compileBody` ?
And isn't that going to break `makeReturn` ?

> @body is expected to be a Block.

Will fix.

Thanks

**Comment by satyr** [comment]
> would be to invert tokens in the lexer

Yep, you'd need to hack lexer.

> Just using @index then ?

`@index` and `@item` would be in the `let` parameters beforehand.

> Isn't that going to break `makeReturn`?

In this case you _need to_ break it. It should return the whole `let`, not the last expression of `let` body.

**Comment by vendethiel** [comment]
> @index and @item would be in the let parameters beforehand.

Ok, so just before calling compileBody, else there's no access to `@item`.

> In this case you need to break it. It should return the whole let, not the last expression of let body.

Right. So I need to `makeReturn` the `@body` I'm passing to let too.

I see a bit better how that goes. Will hack on it after lunch :).Thanks again.

**Comment by vendethiel** [comment]
Ok, I think this is more correct : 7915ca5...1701fae
(with tests)
- `let for` is not disallowed,currently. Should it be?

> for let own or for own let, or both?

just inverting `for`/`let` currently, as I said

**Comment by vendethiel** [comment]
@satyr are you okay with that ? Do you want me to add/change something, rule-wise or syntax-wise ?
Can you squash or do I need to reset hard + paste the files ? (I can't squash because windows)

**Comment by satyr** [comment]
> `let for` is not disallowed,currently. Should it be?

Yes. Should support `for own let` too.

> are you okay with that ?

Doesn't work quite right in nested cases. Try e.g.:

```
*while a
  for let k in o
    return k
```

Similarly, any `break`/`continue` directly under `for let` should be an early error.

**Comment by vendethiel** [comment]
2da664bb1e4ed47fc8ed3cc1e03ded4e913457c9

> Should support for own let too.

Done. Disallowed `let for`

---

> Similarly, any break/continue directly under for let should be an early error.

Not sure how to with `continue`. because of (or thanks to) [While::addBody](https://github.com/satyr/coco/blob/master/src/ast.co#L1629)

``` coffee
for let a in b
  continue
```

will get optimized away and `@getJump!` will return nothing.
However this throws : 

``` coffee
for let a in b
  1
  continue
```

---

No idea how to properly exclude `return` from `@getJump!` because it has no `verb`.
Here's my (dirty!) code : 

``` coffee
      if @body.getJump!
        that instanceof Return or that.carp 'inconvertible statement'
```

---

For 

``` coffee
eq '1', ''+for let a in [0]
  return 1
```

I get an error because of (or thanks to, again) [Node::compileClosure](https://github.com/satyr/coco/blob/master/src/ast.co#L30). I don't mind adding a `and not @let` but it seems very dirty, again. Another flag, like `@allowJumps` ? (added in `makeLet`, ie). If I fix that everything should work (more or less?)

---

> ```
> *while a
>   for let k in o
>     return k
> ```

Fails due to my previous point

**Comment by satyr** [comment]
I guess I give up tutoring this time. Will get my hands dirty.

**Comment by vendethiel** [comment]
Thanks for both!
