### ISSUE TITLE
Disallow variable modification in let when already in scope

### ISSUE THREAD

**Issue by vendethiel** [satyr/coco#166]
Hi, I ran across this bug and I wanted to know if there was a way to disallow this :

``` coffeescript
for {id, name, icon} of records
 let id
  name = if icon? "#icon#name" else "
```

coco generates a fn with "var name" in it, which makes the reference to name later nonfunctional.
Is it possible to add some kind of static checking to avoid that ?

**Comment by satyr** [comment]
> `for {id, name, icon} in records`

You mean `of`?

> `let id`

Here `let` creates a new function scope. You need to use either `:=` or a different name than `name`.

**Comment by vendethiel** [comment]
(I meant of, that's just an habit with foreaches)

as for the function scope creation, I didn't see that this way, but I guess it makes perfect sense.
