### ISSUE TITLE
export function

### ISSUE THREAD

**Issue by jan-swiecki** [satyr/coco#167]
module.co:

```
export (x)->
```

main.co:

```
fn = require './module.co'
console.log typeof fn
```

prints `object`. How do I make this return `function` type? (like `module.exports = (x)->`)

**Comment by jan-swiecki** [comment]
How do I mark this as a question?

**Comment by vendethiel** [comment]
You have to actually name the export. `export a` or `export foo: bar`

**Comment by satyr** [comment]
Since assigning to `module.exports` is a Node.js specific feature and doesn't have the DRY problem, we don't offer a sugar for it. Simply do `module.exports = -> ...`.

**Comment by jan-swiecki** [comment]
Got it! Thank you!
