### ISSUE TITLE
Soak property copy

### ISSUE THREAD

**Issue by vendethiel** [satyr/coco#171]
I don't know if there's already a way to do what I want to do (probably), but I'm looking for a way to soak property copy, in exemple :

```
C:: <<<
 a:? 3
```

**Comment by satyr** [comment]
With what effect exactly?

Maybe see: #50

**Comment by vendethiel** [comment]
It'd be the same as

```
C::a ?= 3
```

**Comment by qqueue** [comment]
Usage here: https://github.com/qqueue/html5chan/pull/3/files#L14L27:

```
Element:: <<<
  prepend: !->
    @insertBefore do
      mutation-macro @@
      @firstChild
  append: !->
    @appendChild mutation-macro @@
# and so on
```

I like the idea of  `<<<?` being sugared as

``` coco
stuff <<<? other
```

``` javascript
soak_import(stuff, other)

function soak_import(base, ext) {
  for (var p in ext) {
    if (!(p in base) && {}.hasOwnProperty.call(ext, p)) {
      base[p] = ext[p]
    }
  }
  return base
}
```

and for the optimized case, the same logic as a soak assignment.

Pretty small set of use cases though, for sure.

**Comment by satyr** [comment]
Cascade may work better there:

```
Element::
  &prepend ?= !-> ...
```

> `if (!(p in base)`

This would have to be `if (base[p] == null` to match `?=`. Unlike `<<<` and `<<<<`, it's not immediately clear what condition we should use here.

This plus:

> Pretty small set of use cases

left #50 unresolved.
