### ISSUE TITLE
Ace-mode fails to highlight regex-splitting

### ISSUE THREAD

**Issue by vendethiel** [satyr/coco#186]
Not sure _how_ it should do it (is it possible with regexps without ugly hacks ?) but ace-mode fails to highlight `a / / /`

**Comment by qqueue** [comment]
The vim-coco plugin also has trouble with regex highlighting, FWIW. The ambiguities with division and regexes starting with spaces are really hard to account for in simple syntax highlighting engines.

The `<expr> / <regex literal>` as sugar for `split` does tend to create most of the ambiguities that break syntax highlighters. Maybe somehow special-case the engines in ace-mode and vim-coco to handle that better.

``` coco
# tricky :
breadcrumbs = window.location.pathname / \/
```

**Comment by vendethiel** [comment]
do we consider spaces should be \s ?
