### ISSUE TITLE
Auto-super back unless hushed

### ISSUE THREAD

**Issue by vendethiel** [satyr/coco#188]
Since I'm regularly bitten by this, I'd like to have auto-super in the constructor with the ability to hush it lile for function returns. (There's probably edge cases I'm not thinking off right now)

**Comment by qqueue** [comment]
So you're suggesting

``` coco
class A extends B
  ->
    stuff
# =>
class A extends B
  ->
    super ...    
    stuff
```

?

I was going to say "but no other OO languages implicitly call `super`!", but I can see the parallels with the implicit return and how this might be desired after some thought.

Some questions remain: Would `super` be called first or last? If `super` is _explicitly_ called somewhere else in the constructor, should the implicit call be added (like implicit return)?

**Comment by vendethiel** [comment]
Probably at the beginning, but it may be possible to look for a "super" in the block (like "that" or "it") and disable the implicit super in that case.

As for the "no other languages", well, I know many languages auto-supering constructor if no constructor is defined, but coco doesn't do it either in this case

**Comment by satyr** [comment]
Smelly. We know implicit-return bit many, which led to the hacky _hushing_.

**Comment by vendethiel** [comment]
Yeah, actually that's not interesting. If coco had autosuper (when no super defined), it'd take only `->` which would be as readable

**Comment by satyr** [comment]
> auto-supering constructor if no constructor is defined, but coco doesn't do it either in this case

This feature has a better chance now that [ES6 draft](http://wiki.ecmascript.org/doku.php?id=harmony:specification_drafts) adopted it. This proposal is much worse.

**Comment by vendethiel** [comment]
Yes. Yes it is, and it's a truely good news you're reconsidering this - thanks ES6.

**Comment by vendethiel** [comment]
Closing this as it's not related to autosuper
