### ISSUE TITLE
No-op argument in backcall

### ISSUE THREAD

**Issue by vendethiel** [satyr/coco#196]
Maybe same as #194 but `, arg <- b` compiles to `b(function (arg) {});`
`(, arg) <- b` compiles correctly

(also, would it be interesting to give the backcall the ability to be alone, so that we can return a function or something ?)

**Comment by satyr** [comment]
You can't omit parens there. Just use the formal syntax (`(, arg) <- b`) when ambiguous.

```
$ coco -bcs
    a
    , b <- c

    a
    (, b) <- c

c(function(a, b){
  a;
  return c(function(arg$, b){});
});
```
