### ISSUE TITLE
Allow `for` piping

### ISSUE THREAD

**Issue by vendethiel** [satyr/coco#201]
Basically just this : 

```
for a
 1
|> c
```

(maybe allowing this ? =>)

```
for a in b
 1
.c
```

**Comment by satyr** [comment]
The former works on master.

As for the latter, that would mean allowing every possible construction to be dot-accessible. We might invoke some more ambiguities in some situations:

```
f ->
  a
.p
# `f(->).p` or `f((->).p)` ?
```

**Comment by vendethiel** [comment]
Not sure how that's an ambiguity since it has been a specialcase since coffee. I wasn't thinking about this behavior, but more imitating Ruby's `end...` one. Not sure that's as interesting as for piping tho.

``` coffee
if foo
 bar
else
 baz
.bat
```

being the same as

``` coffee
(do ->
 if foo
  bar
 else
  baz
)bat
```

**Comment by satyr** [comment]
This particular specialcase (`.` after block closing implicit call) has been justified because `-> ...` etc can't directly be dot-accessed.

> Not sure that's as interesting as for piping tho.

It's technically possible but probably YAGNI.

**Comment by vendethiel** [comment]
Thought so. Having the former is enough for me, but some cases are interesting.
I'd love to be able to do

```
bar =
 * \abc
 * \def
.join ' '
```

**Comment by satyr** [comment]
That's exactly the can of worms I'm afraid to open; it's not immediately clear what's going on.

Following your `if` examples, it would parse as:

```
(bar =
  \abc
  \def
).join ' '
```

but the intention is probably:

```
bar = [
  \abc
  \def
].join ' '
```

**Comment by vendethiel** [comment]
I understand your concerns, and I know you're right, as usual.

**Comment by satyr** [comment]
That said, it's certainly convenient to be able to:

```
bound = ->
  ...
.bind foo

zs = for x of xs
  ...
.concat ys
```

rather than:

```
bound = (->
  ...
)bind foo

zs = do
  for x of xs
    ...
.concat ys
```

It should be safe to make literal functions and _"KEYWORD Expression? Block"_ constructions chainable.

**Comment by vendethiel** [comment]
For the second part, yes. For the first part, maybe I'd say no for consistency, as we saw before

**Comment by satyr** [comment]
Discluding function literals:
- doesn't satisfy the `.bind` use case.
- is also incosistent, because of named `function`s.

Lemme rephrase: make things that require _Block_ chainable.

**Comment by vendethiel** [comment]
That's interesting. Does that mean dropping the `OUTDENT DOT` specialcase in `addImplicitParentheses`? 'Cause I think that's the most common use case.

**Comment by satyr** [comment]
> Does that mean dropping the `OUTDENT DOT` specialcase

Nope. Being able to chain from implicit calls is far more important.
