### ISSUE TITLE
Infuse that

### ISSUE THREAD

**Issue by vendethiel** [satyr/coco#202]
Adding `or name is \that` [here](https://github.com/satyr/coco/blob/master/src/ast.co#L1750) (maybe) to allow for anaphoric conversion to be infused.

``` coffee
while r.exec str then let
  # fancy stuff
```

Is that useful enough?

**Comment by satyr** [comment]
- `While` doesn't have `::infuseIIFE`.
- We don't cross scope for `that`.

Isn't `let that` enough?

**Comment by vendethiel** [comment]
It is. Bumping on `for let` (#164) while I'm at it :p.

**Comment by satyr** [comment]
Patches welcome. :p

**Comment by vendethiel** [comment]
I'm working on it :). Just having some windows issues because I have to run `node lib/blah` instead of `bin/blah`.
