### ISSUE TITLE
Ranges, Slices, Splices, Loops

### ISSUE THREAD

**Issue by ggRalf** [satyr/coco#21]
Any thoughts of integrating this in coco?

https://github.com/jashkenas/coffee-script/issues/835

**Comment by satyr** [comment]
See https://github.com/jashkenas/coffee-script/issues/issue/746 for why they were removed in the first place.

**Comment by ggRalf** [comment]
Hmm, ok. I really like ranges and slicing. I'm very used to it from Python.
But if there is no way to translate them consistently to Javascript its probably better to leave them out. Sad...
