### ISSUE TITLE
compiler option: target platform

### ISSUE THREAD

**Issue by aeosynth** [satyr/coco#210]
say i'm building a mobile app, and have access to all the latest js features; i'd like to pass a flag to the compiler, telling it to use those features instead of shims

**Comment by vendethiel** [comment]
Good "shims" are usually faster than the native implems, I remember @jdalton 's talk about that.

**Comment by aeosynth** [comment]
so keep the fast shims

**Comment by jdalton** [comment]
To clarify, if you're using newer native methods, and then wanting to support browsers that don't have them, your shims should follow the spec. This will make them slower, but necessary if you are putting shims onto `Array.prototype` or other builtins.

To keep things speedy I've used utility methods instead that can opt-in to native use when it's proven faster for given environments. This allows me to avoid following spec so close that it hurts perf for fallbacks while getting the speed of native when it's relevant.

**Comment by satyr** [comment]
We quit simulating `[].indexOf` for similar reasons.

**Comment by aeosynth** [comment]
are there _any_ shims coco uses which have worse performance than native methods? if not, this issue can be closed as pointless

**Comment by satyr** [comment]
> are there any shims coco uses which have worse performance than native methods?

None atm I believe.

> if not, this issue can be closed as pointless

Alrighty.

**Comment by jdalton** [comment]
If you point me to the file w/ the shims I can do a quick review as well.
