### ISSUE TITLE
`~!` as `.call(this)`

### ISSUE THREAD

**Issue by vendethiel** [satyr/coco#211]
Pretty minor. [Here ?](https://github.com/satyr/coco/blob/master/src/lexer.co#L440) (I'd like to avoid creating mess then "will get my hands dirty" 'cause what I did was pure crap)

`a.b~!` => `a.b.call(this)`

(since we already have `~` as bound access.)

**Comment by satyr** [comment]
Desugaring to what, `a.b.~()`? Doesn't look right as we don't allow `a.b.()`.

**Comment by vendethiel** [comment]
Even if it doesn't really make sense for a simple call (`.()`), that could go beyond `!`.
I don't really mind the syntax - I just chose that because that was composed of bound access and bang call.

``` livescript
a~(1) # a.call(this, 1)
a~! # a.call(this)
# but it doesn't look alike this :
a ... # a.apply(this, arguments)
```

**Comment by satyr** [comment]
Note that `a.b.~(c)` is already taken.

**Comment by vendethiel** [comment]
Ah, indeed, `a.(b)` is taken. My bad, I didn't even thought about that. Not sure what then.

**Comment by vendethiel** [comment]
related : gkz/LiveScript#249, proposing postfix `@`

**Comment by redexp** [comment]
how about this?

``` coffeescript
a..(1) # a.call(this, 1)
```

**Comment by redexp** [comment]
and extend `a...` with params

``` coffeescript
a...([a, b]) # a.apply(this, [a, b])
a...(b) # a.apply(this, b)
```
