### ISSUE TITLE
spread call miscompilation

### ISSUE THREAD

**Issue by edef1c** [satyr/coco#222]
coco: `f ...[x for x of [1, 2, 3]]`
expected compilation:

``` js
var x;
f.apply(null, [(function(){
  var i$, ref$, len$, results$ = [];
  for (i$ = 0, len$ = (ref$ = [1, 2, 3]).length; i$ < len$; ++i$) {
    x = ref$[i$];
    results$.push(x);
  }
  return results$;
}())]);
```

actual compilation:

``` js
var x;
f((function(){
  var i$, ref$, len$, results$ = [];
  for (i$ = 0, len$ = (ref$ = [1, 2, 3]).length; i$ < len$; ++i$) {
    x = ref$[i$];
    results$.push(x);
  }
  return results$;
}()));
```

`f ...([x for x of [1, 2, 3]])` compiles to the correct JS.

**Comment by satyr** [comment]
It's an optimization. `f ...[a, b]` is unrolled to `f a, b` pre-compile.

**Comment by edef1c** [comment]
A mis-optimisation, though?
One of them calls a function with a single array argument, the other calls a function with multiple arguments.

**Comment by vendethiel** [comment]
.apply takes an array of arguments.
