### ISSUE TITLE
own in

### ISSUE THREAD

**Issue by edef1c** [satyr/coco#224]
It'd be nice to have a shortcut for hasOwnProperty.
Proposed syntax:
`own k in o`
Proposed compilation:

``` js
var own$ = {}.hasOwnProperty;
own$.call(o, k);
```

**Comment by satyr** [comment]
That syntax doesn't work.

See also: jashkenas/coffee-script#2103

**Comment by edef1c** [comment]
`o has k` is fine with me too - just some kind of syntax for this would rock.
