### ISSUE TITLE
allows comments in implicit listar

### ISSUE THREAD

**Issue by vendethiel** [satyr/coco#226]
Such as 

``` ls
a =
 'a'
 'b'
 /*
 */
```

**Comment by vendethiel** [comment]
ah, that's one thing we can't do because we don't know where to insert them, right ? feel free to close this if so

**Comment by satyr** [comment]
Assuming you mean _block_ comments, we don't even allow them in explicit arrays:

```
$ coco -bcs
[
  1
  2
  /**/
]

SyntaxError: unexpected `/**/` on line 4
```

**Comment by vendethiel** [comment]
Eh, that's true. Too bad.
