### ISSUE TITLE
Update version number to be valid semver

### ISSUE THREAD

**Issue by dbashford** [satyr/coco#228]
Just a heads up that when you next bump the version you'll need to add a dash.

See this issue for reference maxtaco/coffee-script#73

so, `0.9.2b` when bumped will need to be `0.9.2-c`, for example.

**Comment by vendethiel** [comment]
On a patch version ? I love when npm does breaking changes like that -_-.

**Comment by satyr** [comment]
The direct `b` for _beta_ was a habit I picked up from Mozilla (e.g. 25.0a1 for current Nightly). Didn't realize it was semver-invalid.

**Comment by vendethiel** [comment]
I think it's semver rather than semvar

**Comment by satyr** [comment]
Doh.

**Comment by dbashford** [comment]
That has always been invalid, but no one really cared all that much.  It still reads well.  NPM just started caring with `1.3`.
