### ISSUE TITLE
a-b desugars to aB instead of a - b

### ISSUE THREAD

**Issue by markussieber** [satyr/coco#238]
are you serious about this?

in my opinion a-b should be a - b.  Which other language translates this to aB like current coco?!

what exactly is your reason for allowing  is-array when the underlying function is isArray? the developer should write isArray and nothing else...

**Comment by vendethiel** [comment]
#137. Other languages have spinal-cased identifiers (like lisp, perl 6, etc)

**Comment by michaelficarra** [comment]
@markussieber: Wow, that's a very authoritarian take on programming language design you have there.

**Comment by vendethiel** [comment]
Don't feed the troll :p

**Comment by satyr** [comment]
> (like lisp, perl 6, etc)

True that it's less of a trap in these languages, e.g.: `(- a b)` `$a-$b`

**Comment by markussieber** [comment]
i dont want to troll, sorry if my complaints looked like it. I see in #137  that you already discussed this feature. I am against it, but that should not matter :)
thanks for coco except this matter i really like the language.
