### ISSUE TITLE
Include source

### ISSUE THREAD

**Issue by jasonl99** [satyr/coco#243]
I think it would be useful to include the source of each method (minus the documentation that has already been extracted) in an initially-collapsed element.  I've tried to look at the code and figure out how to do this, but it's way over my head :).

**Comment by vendethiel** [comment]
What do you call an "initially-collapsed element"? You mean to compile

``` coffee
x = -> 5 + it
```

to

``` js
var x;
x = function (it) {
  /*
 5 + it
 */
  return 5 + it;
}
```

**Comment by jasonl99** [comment]
Oh, snap.  I put this in the wrong repository.  Sorry!
