### ISSUE TITLE
Keyless variable in implicit object

### ISSUE THREAD

**Issue by vendethiel** [satyr/coco#244]
We have `{a}` in the case of an explicit object, but I don't quite seem to remember a feature that'd allow this kind of thing to be simplified:

``` coffee
a =
  b: b
  # since we have:
  ...: c
```

**Comment by satyr** [comment]
If you must:

```
a =
   ...: {b}
```

**Comment by vendethiel** [comment]
Hm, thanks. Would you be interested in supporting it, or not at all?

**Comment by satyr** [comment]
Support what?

**Comment by vendethiel** [comment]
a single-variable variation

**Comment by satyr** [comment]
But how? You can't blindly consume non-properties into a braceless object.

E.g. `f p: q, g()` wants to be `f({p: q}, g())`, not `f({p: q, g: g}())`.

**Comment by vendethiel** [comment]
no, not blindly. I was thinking of some syntax, like `*: a`, but this might just be good enough.
