### ISSUE TITLE
Propagate line numbers from parser to AST

### ISSUE THREAD

**Issue by satyr** [satyr/coco#35]

**Comment by andrewschaaf** [comment]
https://github.com/andrewschaaf/coffee-script/commit/8270ce2486fcdce530d32199b9ec11d8e24683c8

https://github.com/jashkenas/coffee-script/pull/955

**Comment by satyr** [comment]
closed by 71eb9d8e9bbcc7b4db270d0d1584db2063da1e8f; nodes now receive line numbers from parser, reporting them on error
