### ISSUE TITLE
typo in readme

### ISSUE THREAD

**Issue by jasonkuhrt** [satyr/coco#44]
Install instructions state:
git clone git:github.com/satyr/coco.git && cd coco && bin/coke i

But should be:
git clone git://github.com/satyr/coco.git && cd coco && bin/coke i

**Comment by satyr** [comment]
closed by 4a0f5ca0947b602284ffb7fa0edf03a8b6311602

**Comment by jasonkuhrt** [comment]
Thanks satyr.
