### ISSUE TITLE
npm install coco link bin error

### ISSUE THREAD

**Issue by stuarts** [satyr/coco#47]
Apparently there is a problem with package.json. According to [isaacs](https://github.com/isaacs/npm/issues/684#issue/684/comment/846046)  the bin hash should be filenames not module ids.

~ $ npm install coco --loglevel verbose npm info it worked if it ends with ok
npm verb cli [ 'install',
npm verb cli 'coco',
npm verb cli '--loglevel',
npm verb cli 'verbose' ]
npm info using npm@0.3.15
npm info using node@v0.4.2
npm verb config file /Users/stuarts/.npmrc
npm verb config file /Users/stuarts/local/etc/npmrc
npm verb install [ 'coco' ]
npm verb install [ 'coco' ]
npm verb install pkglist [ 'coco' ]
npm verb must install [ 'coco' ]
npm verb install coco
npm verb must install? [ [ 'coco' ], true ]
npm verb GET coco
npm verb etag "2V412V9E96NYDOLEOXV5L3HMB"
npm verb response http://registry.npmjs.org/coco npm verb etag coco from cache
npm verb Supported versions [ 'coco@0.1.3',
npm verb Supported versions 'coco@0.1.4',
npm verb Supported versions 'coco@0.1.5',
npm verb Supported versions 'coco@0.1.6',
npm verb Supported versions 'coco@0.2.0',
npm verb Supported versions 'coco@0.2.1',
npm verb Supported versions 'coco@0.2.2',
npm verb Supported versions 'coco@0.3.0',
npm verb Supported versions 'coco@0.3.1',
npm verb Supported versions 'coco@0.3.2' ]
npm verb coco tag latest
npm verb install coco@0.3.2
npm verb must install? [ [ 'coco', '0.3.2' ],
npm verb must install? true ]
npm verb coco@0.3.2 exact
npm verb caching /Users/stuarts/local/lib/node/.npm/.cache/coco/0.3.2/package.json
npm verb install list [ [ 'coco', '0.3.2' ] ]
npm verb mkdir done: /Users/stuarts/local/lib/node/.npm/coco/0.3.2
npm verb unpackTar uid, gid [ undefined, undefined ]
npm verb success gzip "--decompress" "--stdout" "/Users/stuarts/local/lib/node/.npm/.cache/coco/0.3.2/package.tgz"
npm verb success tar "-mvxpf" "-" "-C" "/Users/stuarts/local/lib/node/.npm/coco/0.3.2"
npm verb unpacked, building coco,0.3.2
npm verb caching /Users/stuarts/local/lib/node/.npm/coco/0.3.2/package/package.json
npm info preinstall coco@0.3.2
npm verb deps being resolved [ { name: 'coco',
npm verb deps being resolved description: 'Unfancy CoffeeScript',
npm verb deps being resolved keywords:
npm verb deps being resolved [ 'language',
npm verb deps being resolved 'compiler',
npm verb deps being resolved 'coffeescript',
npm verb deps being resolved 'javascript' ],
npm verb deps being resolved author:
npm verb deps being resolved { name: 'satyr',
npm verb deps being resolved email: 'murky.satyr@gmail.com',
npm verb deps being resolved url: 'http://satyr.github.com' },
npm verb deps being resolved version: '0.3.2',
npm verb deps being resolved homepage: 'http://satyr.github.com/coco/',
npm verb deps being resolved repository:
npm verb deps being resolved { type: 'git',
npm verb deps being resolved url: 'git://github.com/satyr/coco.git' },
npm verb deps being resolved licenses:
npm verb deps being resolved [ { type: 'MIT',
npm verb deps being resolved url: 'https://github.com/satyr/coco/raw/master/LICENSE' } ],
npm verb deps being resolved engines: { node: '>=0.2.6' },
npm verb deps being resolved directories: { lib: './lib', bin: './bin' },
npm verb deps being resolved main: './lib/coco',
npm verb deps being resolved bin:
npm verb deps being resolved { coco: './lib/command',
npm verb deps being resolved coke: './lib/coke' },
npm verb deps being resolved id: 'coco@0.3.2',
npm verb deps being resolved engineSupported: true,
npm verb deps being resolved npmVersion: '0.3.15',
npm verb deps being resolved nodeVersion: 'v0.4.2',
npm verb deps being resolved files: [ '' ],
npm verb deps being resolved defaultsLoaded: true,
npm verb deps being resolved dist:
npm verb deps being resolved { shasum: 'd5aff68b204e5f5f84f7db0298b2af6d2da3370e',
npm verb deps being resolved tarball: 'http://registry.npmjs.org/coco/-/coco-0.3.2.tgz' },
npm verb deps being resolved _bundledDeps: [] },
npm verb deps being resolved [] ]
npm verb linkBins coco@0.3.2
npm verb linkBin coco ./lib/command
npm verb linkBin coke ./lib/coke
npm verb linkMans coco@0.3.2
npm ERR! failed to link bins
npm ERR! install failed Error: ENOENT, No such file or directory '/Users/stuarts/local/bin/coco@0.3.2'
npm info install failed rollback
npm info uninstall [ 'coco@0.3.2' ]
npm verb removing [ [ 'coco', '0.3.2' ] ]
npm verb from cache /Users/stuarts/local/lib/node/.npm/coco/0.3.2/package/package.json
npm info preuninstall coco@0.3.2
npm info uninstall coco@0.3.2
npm info auto-deactive not symlink
npm verb uninstall coco@0.3.2 remove links
npm verb uninstall coco@0.3.2 remove bins
npm verb uninstall coco@0.3.2 remove public modules
npm info postuninstall coco@0.3.2
npm verb uninstall coco@0.3.2 remove package dir
npm info uninstall coco@0.3.2 complete
npm info install failed rolled back
npm ERR! Error: ENOENT, No such file or directory '/Users/stuarts/local/bin/coco@0.3.2'
npm ERR! Report this entire log at http://github.com/isaacs/npm/issues
npm ERR! or email it to npm-@googlegroups.com
npm ERR! Just tweeting a tiny part of the error will not be helpful.
npm ERR! System Darwin 10.6.0
npm ERR! argv { remain: [ 'coco' ],
npm ERR! argv cooked:
npm ERR! argv [ 'install',
npm ERR! argv 'coco',
npm ERR! argv '--loglevel',
npm ERR! argv 'verbose' ],
npm ERR! argv original:
npm ERR! argv [ 'install',
npm ERR! argv 'coco',
npm ERR! argv '--loglevel',
npm ERR! argv 'verbose' ] }
npm verb exit [ 2, true ]
npm not ok

**Comment by satyr** [comment]
Thanks. I've pushed a [fix](https://github.com/satyr/coco/commit/d3aa5fd56bf026e1b41a338510b91db73527c8f2), but can't test/upload it right now as npm server is giving me "unauthorized Name or password is incorrect."

**Comment by satyr** [comment]
Patched 0.3.2 with above fix and published as 0.3.3. Let me know if it works.

**Comment by stuarts** [comment]
Yep, it's working. Cool, thanks.
