### ISSUE TITLE
Support language filters?

### ISSUE THREAD

**Issue by jasonkuhrt** [satyr/coco#49]
Would it a terrible idea to allow other languages within coco?

Here's a simple example of what I am thinking:

```
paragraph = 
    :markdown
    Hello, 
    ======
    Today is a *fine* day.

$('#welcome-message').inject paragraph
```

The :markdown is just an example of how one might signify the beginning of a new language block. I guess coco would need to have a 'hook' for authors to plugin/reference other language compilers. I imagine it wouldn't be _too_ hard to manage that part. The issue may be more the usefulness of such a feature, and enough use-cases to make it worthwhile.

**Comment by satyr** [comment]
The _coco_ cli supports `--require` option for this kind of needs, inheriting from _coffee_.
You can hook into compiling process like this:
    $ cat md_hack.co
    Coco.on \compile (data) ->
      {markdown} = require \markdown
      data.ast.traverseChildren ->
        return unless it.constructor.name is \JS and /^<md>/test it.code
        it.code = JSON.stringify markdown.toHTML it.code.slice 5
        void
      , true

```
$ coco -r ./md_hack.co -s
console.log `<md>
  Hello,
  ======
  Today is a *fine* day.
`

<p>  Hello,
  ======
  Today is a <em>fine</em> day.</p>
```

See also:
- https://github.com/jashkenas/coffee-script/wiki/%5BExtensibility%5D-Hooking-into-the-Command-Line-Compiler
- http://blog.davidpadbury.com/2010/12/09/making-macros-in-coffeescript/

**Comment by jasonkuhrt** [comment]
Thanks Satyr. I will test / read further into this. Closed.
