### ISSUE TITLE
Regex.test() shorthand

### ISSUE THREAD

**Issue by fbuchinger** [satyr/coco#51]
How about a Regex.test() shorthand borrowed from perl

```
mystr =~ /^UNICODE\0/ // --> /^UNICODE\0/.test(mystr)
```

maybe coco could also take care of compiling/caching the regexes.

**Comment by satyr** [comment]
What are the benefits, beyond saving a few bytes?

**Comment by adrusi** [comment]
it does look nicer, and since coco is a cross between ruby, python and perl, and since both ruby and perl have `=~`, it seems appropriate

**Comment by satyr** [comment]
> it does look nicer, ..., it seems appropriate

Debatable.
- It tends to be [misremembered](https://github.com/jashkenas/coffee-script/issues/1378), which is a bad sign.
- The usage varies across languages:
  - Perl uses it for replacement as well.
  - Ruby uses it bidirectional: `s =~ /./` <=> `/./ =~ s`
  - Groovy takes string as regex (`/\./ == "\\."`), and it returns the match object (or `null`)
- We overload `~` in a few, non-regex-related places already.

**Comment by adrusi** [comment]
It's not very imortant, and your right, it's hard to remember what all the different languages do with it. With operator overloading it should be replicatable.

**Comment by satyr** [comment]
Closing, assuming understood.
