### ISSUE TITLE
`constructor` shorthand

### ISSUE THREAD

**Issue by satyr** [satyr/coco#53]
As in `prototype` ⇔ `::`.

**Comment by satyr** [comment]
closed by 093376808c8297e4884e21bb0a04f0ee6e4894d1; `..` as `constructor`

**Comment by michaelficarra** [comment]
How is `[a..3]` not ambiguous now?

**Comment by satyr** [comment]
> How is `[a..3]` not ambiguous now?

That compiled to `[a[.3]]` before, which was less useful.
