### ISSUE TITLE
function variable "it" conflicts with jasmine (et al?)

### ISSUE THREAD

**Issue by jasonkuhrt** [satyr/coco#54]
[Jasmine](https://github.com/pivotal/jasmine) has syntax like...

```
describe "operators as functions", (coco_do_not_use_it)->

    it "a + function capable of adding an arbitrary count of numbers", ->
        expect op['+'](3,1,5,11)
        .toEqual(20)
```

which causes problems because of the `it`. My current solution is to throw in a dummy variable in the function arguments.

I'm not sure how you feel about this. Should coco assume that libraries won't/shouldn't use a variable called `it`?

**Comment by satyr** [comment]
> Should coco assume that libraries won't/shouldn't use a variable called `it`?

I'd like to think so. `it` is a stupid name for a global function after all.

Maybe:

```
I = it
describe "operators as functions" ->
    I "am '+', capable of adding an arbitrary count of numbers" ->
        expect op\+ 3 1 5 11
        .toEqual 20
```

**Comment by jasonkuhrt** [comment]
Ok, thanks for the suggestion and clarification.

**Comment by jasonkuhrt** [comment]
closed.
