### ISSUE TITLE
Request: Vim highlighting

### ISSUE THREAD

**Issue by jasonkuhrt** [satyr/coco#55]
I noticed there is coco highlighting for the cloud editor. If a port becomes available for vim that would be great (for me at least).

**Comment by satyr** [comment]
If someone makes it available that would be great (for me to start using vim).

**Comment by jasonkuhrt** [comment]
I'll try to convert your work for the cloud editor into vim but it may be a few months.

**Comment by satyr** [comment]
Started https://github.com/satyr/vim-coco.

I'm totally new to Vim, so any help is appreciated.

**Comment by jasonkuhrt** [comment]
Thanks for starting this Satyr. When I said "a few months" I was hoping I'd have the expertise by then but alas vim/coco combo hasn't been the focus of my time lately. At the very least I will try out what you've done and post some ideas on the issues if I think of an idea.

One idea right now is to provide special formatting (color? italics? underline? etc.) to the expression being returned to help visually see what is happening in the code. Not sure if that is possible without too much overhead though...
