### ISSUE TITLE
"parenless method chains" and "parenless call do" incompatibility

### ISSUE THREAD

**Issue by adrusi** [satyr/coco#61]
I tried out the parenless method-chain feature, which looked very useful, but I noticed that it's not very parenless if you have 0-argument methods on the chain.

```
_  = require "underscore"
console.log do
  _ [1, 2, 3, 4, 5]; .chain(); .rest(); .without 3; .value()
end
```

is not parenless, you can't add `do` parenless calls, because then `unexpected DOT` is thrown since `do` sees what appears to be an out of place `.`

an ideal syntax would be:

```
_  = require "underscore"
console.log do
  _ [1, 2, 3, 4, 5]; do .chain; do .rest; .without 3; do .value
end
```

**Comment by satyr** [comment]
Since `do` is a unary prefix operator (unless followed by a block), `do .value` doesn't make sense in the same way `new .value` doesn't.

As for eliminating `()` somehow, there were [repeating](https://github.com/jashkenas/coffee-script/issues/988) [requests](https://github.com/jashkenas/coffee-script/issues/1257) on CoffeeScript, all rejected. The rational basically goes like:
1. Because _it's just JavaScript,_ `a.b` can't implicitly be `a.b()`--there needs to be some indication.
2. Replacing `()` with another symbol is a possiblity, but there seems no such symbol that feels more _right_. (`a.b!` and the like were proposed, and rejected eventually).
3. `()` is familiar, typable and concise enough as is.

**Comment by satyr** [comment]
You can, however, come up with a _right_ syntax, and be a hero. ;)

**Comment by adrusi** [comment]
Well, this interferes with bitwise OR, but how about pipe characters

```
_ [1,2,3] | do chain | do rest | without 3 | do value
```

You already overrode bitwise NOT, so bitwise OR is just as unused.

**Comment by satyr** [comment]
> `_ [1,2,3] | do chain | do rest | without 3 | do value`

Operator choice aside, isn't `do` redundant in this case?

> You already overrode bitwise NOT, so bitwise OR is just as unused.

To do the same, its use must be non-viable in JS (thus `g:~->`). `f() | g()` should retain its semantic.

**Comment by adrusi** [comment]
Well, it's not redundant because without `do` it wouldn't execute the function. I assume you don't want Unicode. How about a fat arrow `=>`?

**Comment by satyr** [comment]
> Well, it's not redundant because without `do` it wouldn't execute the function

`a | b` => `a.b` is a little unintuitive as piping usually involves execution of right hand side.
In either case though, unary `do` still doesn't make sense for the same reason as above. (What would `a | +b` mean, for example?)

> How about a fat arrow `=>`?

Workable. In fact, I've been pondering about piping variant that accept any expression, using `<>` as the placeholder of previous value.

```
v => f => g <>, a => <>()
```

↓

```
_ref = f v
_ref = g _ref, a
_ref()
```

This doesn't really eliminate `()` though.

**Comment by adrusi** [comment]
How about 

```
a.b => c => d \e
```

To

```
a.b.c().d("e");
```

And if you want unix style piping

```
a | b | c \d ... | e \f
```

To

```
var _ref = a;
_ref = b(_ref);
_ref = c("d", _ref);
_ref = e(_ref, "f");
```

**Comment by satyr** [comment]
> This doesn't really eliminate `()` though

Wait, it does. As `do` is applicable here: `f.g(a).h()` => `f.g a => do <>h`
Seems unnecessary verbose though.

**Comment by satyr** [comment]
> ```
> a.b => c => d \e
> ```
> 
> To
> 
> ```
> a.b.c().d("e");
> ```

Two issues:
- Readability: It's not visually obvious that `c` accesses and calls.
- Versatility: We have other dot variants (`?.` `.=` etc.). How do you apply them?

**Comment by adrusi** [comment]
I'm not sure there'sa readability problem. An arrow is associated with movement, and therefore an action being taken. I think it's clear enough.

Why not just add the variant symbol between `=` and `>`: `=?>` `==>`. That's a bit ugly, but the placement of the symbol could change: `?=>` `==>` possibly.

**Comment by satyr** [comment]
> I think it's clear enough

The `=>` there has an atypical syntax that shares no precedence in any language I know of (including Coco).

> That's a bit ugly

Not just ugly, but too far. Why add whole new series of syntaxes, only to alias `()`?
Being a minor improvement, the solution should be simple and generic.

**Comment by adrusi** [comment]
Why not just have `obj.do method.withParams "str"` => `obj.method().withParams("str")`. That wouldn't have any conflicts since `do` is reserved in both coco and js

**Comment by satyr** [comment]
> `obj.do method.withParams "str"`

ES5 allows arbitrary identifier after `.`. `obj.do` is valid:

```
$ node -e 'obj = {do: "it"}; obj.do'
it
```

**Comment by adrusi** [comment]
Oh, well. I have nothing, I'll let you know if I cone up with something. That part of es5 seems like a bad idea though, in commonjs you could do `global.do = "str";` but then you couldn't do `console.log(do);`.

**Comment by satyr** [comment]
> in commonjs

_node.js_?

> you could do `global.do = "str";` but then you couldn't do `console.log(do);`

Techinically possible:

```
$ node -e 'global.do = "it"; \u0064\u006f'
it
```

**Comment by adrusi** [comment]
Commonjs is a standard for command line javascipt implementation, including node. It defines require, exports, module, and global

**Comment by satyr** [comment]
> and global

Really? I don't see it in http://wiki.commonjs.org/wiki/Modules/1.1.1.

**Comment by ghost** [comment]
@satyr `global` is implemented in most environments, but it isn't officially part of the CommonJS specification.

**Comment by satyr** [comment]
Closing in favor of #64.
