### ISSUE TITLE
single-element arrays

### ISSUE THREAD

**Issue by jasonkuhrt** [satyr/coco#63]
I am trying to find a easy-as-possible way to create json data.

Here is a segment of data:

```
            content:
                festivals:
                    '<a href="">2011 Official Selection Segenuay</a>'
                    '<a href="">2011 North Carolina</a>'
                articles:
                    '<a href="">2009 La Presse</a>'
                prizes:
                    '<a href="">2010 Best Short (Festival du Nouveau cinema)</a>'
```

There is a problem above:  
- I want `festivals`, `articles`, and `prizes` to be arrays
- But, only `festivals` is an array
- coco thinks I want an array when there is two or more elements nested below, but, a string if only one.

Is this intended? I feel that it should only be a string if I  explicitly want it, like this:

```
            content:
                festivals:
                    '<a href="">2011 Official Selection Segenuay</a>'
                    '<a href="">2011 North Carolina</a>'
                articles:  '<a href="">2009 La Presse</a>'
                prizes: '<a href="">2010 Best Short (Festival du Nouveau cinema)</a>'
```

**Comment by satyr** [comment]
Implicit array requires two or more elements to disambiguate from normal assignment with line break.

```
$ coco -bps
a =
  b

a =
  b
  c

a =
  b
  ...

var a;
a = b;
a = [b, c];
a = [b].concat([]);
```

I'll probably improve the last case to omit useless `.concat([])`.

**Comment by jasonkuhrt** [comment]
What is useful about the first case?

Why not treat it like the second case?

**Comment by jasonkuhrt** [comment]
Oh but I see, the `...` can be used to format as an array if desired..

**Comment by satyr** [comment]
> What is useful about the first case?

Formatting and backward compatibility. Otherwise

```
content:
  festivals: '...'
```

would become

```
({content: [{festivals: '...'}]})
```

**Comment by jasonkuhrt** [comment]
Ah of course. That is obvious, sorry. The `...` is a nice way to format it as an array then. Is that documented? I just searched for `...` in the additions page on the coco wiki. I did not find an instance describing this behaviour? Anyways intuitively I like it.

**Comment by satyr** [comment]
> I did not find an instance describing this behaviour?

Looks like undocumented--sorry about that.

`...` in arguments is only a convenience sugar, meaning `...[]`. It's added primary to support destructuring like:

```
[first, ..., last] = array
```
