### ISSUE TITLE
paren-free calls revisited

### ISSUE THREAD

**Issue by satyr** [satyr/coco#64]
### with arguments
- [coffee#1407](https://github.com/jashkenas/coffee-script/issues/1407)
- #61

8118fd58632f1f4f891c46b6be09d9139f2b753b

```
f a; .g b, c; .h d
```

↓

```
f a .g b, c .h d
```

Line-leading dots are working this way already. Expanding it to spaced dots seems acceptable.
### without arguments
- [coffee#514 ](https://github.com/jashkenas/coffee-script/issues/514)
- [coffee#1257](https://github.com/jashkenas/coffee-script/issues/1257)
- [coffee#1412](https://github.com/jashkenas/coffee-script/issues/1412)

Considering this must beat `()` in both conciseness and readability, postfix `!` is probably the only contender.

```
f().g()
```

↓

```
f!.g!
```

Semiautovivification (with ADI) conflicts, but can be adjusted. (`a!b` wasn't very intuitive anyway.)

**Comment by adrusi** [comment]
Nice, I'm liking it. postfix `!` is much better than `do` because `do func` is actually longer than `func()`. Space leading dots are also very nice.
