### ISSUE TITLE
`arguments` shorthand

### ISSUE THREAD

**Issue by adrusi** [satyr/coco#68]
It would be nice to have a shorthand for the arguments object, like what kaffeine has (`#` -> `arguments[0]` and `#5` -> `arguments[5]`). I can't think of a good syntax without requiring changing the comment syntax. maybe if you required whitespace around bitwise AND we could have `&`, `&1`, `&2`, `&3`, etc., but that would lose consistency, even if it _is_ for an uncommon operator.

if coco had this, it would be easy to write very terse function definitions, useful for functional programming:

```
map (-> & + 1), 1 to 4
```

currently, this requires:

```
map ((x) -> x + 1), 1 to 4
```

which has too many parenthesis and is just not terse enough for a syntax like coco.

also, while on the topic of the length of defining functions, I'd like to point out that kaffeine's way of defining function with brackets (`{ ... }` -> `function() { ... }` and `(a, b) { ... }` -> `function(a, b) { ... }`) is better for passing functions as arguments. I suppose `(-> ... )` is ok, it resembles haskell's `(\ -> ... )`.

**Comment by satyr** [comment]
> It would be nice to have a shorthand for the arguments object, like what kaffeine has (`#` -> `arguments[0]` and `#5` -> `arguments[5]`)

```
$ coco -bpe '-> @@5'
(function(){
  return arguments[5];
});
```

> `map ((x) -> x + 1), 1 to 4`

```
$ coco -e '[1 to 4]map -> it + 1'
[ 2, 3, 4, 5 ]
```
