### ISSUE TITLE
Super Shenanigans

### ISSUE THREAD

**Issue by ceymard** [satyr/coco#74]
```
class A
    (@msg) ->

class B extends A
    (msg) ->
         super msg

console.log B("my message").msg
```

Expected : "my message", Result: "undefined"

`super ...` translates into superclass.apply(this, arguments)
but `super msg` to superclass(arguments), which obviously won't touch the instance.

Shouldn't `super <whatever>` translate into super.call(this, <whatever>) ?

**Comment by satyr** [comment]
`super` is simply a reference to the superfunction. This gives you greater flexibility (e.g. `supername = super.displayName`), but makes some cases a little verbose (e.g. `super.call this, msg`) in turn.

> `class B`

`class B extends A`?

**Comment by ceymard** [comment]
If the only utility of the super function is anyways to be called with `this`, maybe in the context of a function call `super arg1, arg2` should be desugared to `superclass.call this, arg1, arg2`, and to `superclass` the rest of the time.

This way, we could still access `super.displayName`, which is really useful, and have the whole `.call this,` hidden away from us the rest of the time. Plus, it wouldn't break code, this `super.call` would still resolve to `superclass.call` (same goes for `apply`)

Anyways, the whole `super ...` is a little counter intuitive : why should it be the only one to get desugared this way ? Reading the doc, I thought for a time that `super` did that for everything :)

So at least, if there is no plan to change this behaviour, I think `super ...` should disappear, since it can lead to thinking errors...

**Comment by satyr** [comment]
> maybe in the context of a function call `super arg1, arg2` should be desugared to `superclass.call this, arg1, arg2`, and to `superclass` the rest of the time.

That'd be an exceptional rule for otherwise simple `super` reference, hurting consistency somewhat.

> Anyways, the whole `super ...` is a little counter intuitive : why should it be the only one to get desugared this way ?

This syntax isn't `super`-specific (search for _thisplat_ in [additions](https://github.com/satyr/coco/wiki/additions)).

```
$ coco -bpe 'f ...'
f.apply(this, arguments);
```

**Comment by ceymard** [comment]
Maybe then could we think of another keyword do have `super` applied with the current `this` ?

I still am interested to not have to write `.call this,` everytime, as it is a little cumbersome...

I agree about the consistency, had not realized fully what the thissplat was about.

**Comment by satyr** [comment]
My assumption was that calls to `super` don't happen that often, and `super ...` covers the most cases.

**Comment by ceymard** [comment]
Renamed the issue to more accurately describe the "problem".

I agree with what you say, but at around 50%. I think that coco manages to solve so many not-so-trivial programming patterns rather elegantly. I'm a little disappointed that we have to pass through something less elegant for something that is not so uncommon in OOP.

Especially, coco hides a lot of the javascript strange things, and the whole `this` debacle ought to be really hidden to the end, hence my request.

Maybe we could leave this issue open for a little time to at least have some kind of reflexion about it ?

**Comment by satyr** [comment]
> Especially, coco hides a lot of the javascript strange things, and the whole `this` debacle ought to be really hidden to the end, hence my request.

Coco doesn't try to _hide_ JS quirks. Rather, its goal is to _expose_ hidden goods. (For example, it provides [cloning](https://github.com/satyr/coco/issues/6) to encourage [prototypal OO](http://javascript.crockford.com/prototypal.html) over `class`). You can't really avoid `this` interactions as long as _"It's just JavaScript."_

That said, having to write `super.call this` does feel cumbersome and probably is error prone (especially since `super x` works, but with wrong context). It may be worthwhile to specialcase direct call to `super` as you proposed.

**Comment by ceymard** [comment]
Probably if properly documented, the inconsistency introduced by this special case could be balanced out.

I was thinking about writing a documentation for coco, as I am using it already in all my project - and imposing it to my co-worker, who frequently complains about the lack of it :)

Anyways, maybe here is not really the good place to talk about it (do you have a mailing list ? If not, maybe it would be a good idea to make one ?), but I have been precisely hesitating a lot between using the whole class vs prototypal approach.

In effect, I started with the prototypal, but did not settle on an implementation I thought "clean" enough (ie, without noise). I am currently trying `class`, which is why I encountered the whole `super` thing. But so far, I find it rather nice.

The thing is : I like the syntactic sugar provided by `class` (I hated the whole `prototype` thing is JS), and I feel that the approach of `Object.beget`, `Object.create` is "hacky". Do you have some example program that you did using this approach ? - I am fairly certain that my approach was incomplete.

Btw, I tried in the interpreter of `0.5.4` to do

```
coco> o = {a: 1, b:2}
{ a: 1, b: 2 }
coco> o2 = o{c: 3}
{ c: 3 }
coco> o2
{ c: 3 }
```

I was expecting `{ a: 1, b: 2, c: 3 }`. Was I off ?

**Comment by satyr** [comment]
> (do you have a mailing list ? If not, maybe it would be a good idea to make one ?)

Not sure if we have enough users to warrant one. For now, feel free to open issues and/or edit wiki sections for questions.

> I was expecting `{ a: 1, b: 2, c: 3 }`. Was I off ?

The prettyprinter shows only own properties. (You'd see things like `toString` otherwise.)

```
coco> o2.__proto__
{ a: 1, b: 2 }
```

**Comment by satyr** [comment]
> Do you have some example program that you did using this approach ?

[Our lexer](https://github.com/satyr/coco/blob/master/src/lexer.co) is one.

**Comment by ceymard** [comment]
Is there anyway to have that kind of prototyping while still having functions as constructors ?

I find using `instanceof` fairly useful.

ie. is there a syntax to augment an object using another constructor ? Like for exemple

```
a = new MyObject() # or MyObject() if we want to make complete abstraction of this
a augment AnotherObject # which would call AnotherObject(a)
```

The problem when using the `obj1{...}` syntax is that I can only have `obj1 instanceof Object` - unless I missed something.

I don't know if I'm completely clear, as it is not entirely clear in my head either. In short, I would then like to do

```
a instanceof MyObject => true
a instanceof AnotherObject => true
```

I would still like to use the `@accessor` as I like the syntax.

Also, but I don't know if there is an elegant way to do it, but I would like to have protected-level properties. Your thoughts ?

**Comment by satyr** [comment]
Not sure I get you, but you can always use `isPrototypeOf` to check the inheritance chain.

```
coco> a = {}; b = a{}; c = b{}
{}
coco> a.isPrototypeOf b and b.isPrototypeOf c and a.isPrototypeOf c
true
```

If you are going to rely on type checking heavily though, sticking to `class` and `instanceof` is the way to go.

> I would still like to use the `@accessor` as I like the syntax.

Sure.

> I would like to have protected-level properties.

Protected in what way? Private? Read-only? Example?

**Comment by ceymard** [comment]
> Protected in what way? Private? Read-only? Example?

`protected` as in having a companion object that stores members only accessible to the object.
edit: forget about it. bad idea.

Just like protected in other languages. Currently, there is a way 

> Not sure I get you

I have not been very clear. In fact, I realize that I was not using prototypal inheritance but functional inheritance.

What I did was more in the lines of :

```
trait_one = (specs, instance) ->
    instance ?= {} # this is akin to ~> when using classes
    # do stuff on the instance
    return instance

trait_two = (specs, instance) ->
    instance ?= {} # again...
    # this is what I'd love to be able to do :
    trait_one specs, instance if not instance instanceof trait_one
    # do more stuff on this instance
    return instance
```

Problems with that approach :
- verbose
- ugly

I'll stick with regular-style classes like you said (also for performance reasons). Also, I'll start writing some doc some point in the future.

**Comment by scribu** [comment]
I started using Coco recently and I found the `super ...` vs. `super arg` thing the most confusing.

**Comment by scribu** [comment]
Awesome.
