### ISSUE TITLE
'~>' vs '=>'

### ISSUE THREAD

**Issue by scribu** [satyr/coco#76]
I was wondering why coco uses  `~>` instead of `=>`. I couldn't find any info on that.

I would prefer `=>`, since it's easier to spot.

**Comment by satyr** [comment]
For:
- _bound backcall_ `<~` (`<=` is taken as "less than or equal")
- visual connection between _bound access_ `.~`

**Comment by scribu** [comment]
Makes sense. Thanks for the clarification.
