### ISSUE TITLE
for...of vs. for...in

### ISSUE THREAD

**Issue by scribu** [satyr/coco#78]
Compare:

`for value, key of array`

`for key, value in object`

How about this:

`for value of array`
`for key, value of array`

`for value in object`
`for key, value in object`

**Comment by satyr** [comment]
`for value in object` is unaccetable as that'd be confusing with JS's `for(key in object)`. We want to be as close as JS semantics (hence the `in`-`of` correction from CoffeeScript).

See http://groups.google.com/group/coffeescript/msg/b83e713d4c9a7967 for how the current order came to be in CoffeeScript/Coco.

**Comment by scribu** [comment]
Right. How about something like [for each...in](http://developer.mozilla.org/en/JavaScript/Reference/Statements/for_each...in)?

**Comment by satyr** [comment]
Supporting `for`-`each` doesn't make sense unless we support [E4X](http://www.ecma-international.org/publications/standards/Ecma-357.htm) (which I don't even want to think about).

**Comment by scribu** [comment]
I guess we're stuck with jQuery.each() then. :P

**Comment by satyr** [comment]
> we're stuck with jQuery.each() then

For emulating object values? I think it behaves similar to our `for`-`in`:

```
$.each {a:1 b:2} (k, v) -> console.log k, v  # "a 1" then "b 2"

console.log k, v for k, v in {a:1 b:2}  # same as above
```

**Comment by scribu** [comment]
Yeah, but jQuery.each() handles both arrays and objects.

Anyway, it was more of a joke. `for...of` and `for...in` are fine.
