### ISSUE TITLE
`? =` vs. `?=`

### ISSUE THREAD

**Issue by scribu** [satyr/coco#82]
Compare:

``` coffeescript
a.b? = c
```

``` javascript
if (typeof c != 'undefined' && c !== null) {
  a.b = c;
}
```

with:

``` coffeescript
a.b ?= c
```

``` javascript
a.b == null && (a.b = c);
```

Shouldn't it be the other way around?

I think `?=` makes more sense as the soaking operator, while `a.b?` would remain consistent, no matter on which part of the assignment it appears:

`a.b? = c` or `c = a.b?`

**Comment by satyr** [comment]
Let's see...
- `a.b ?= c` is a conditional assignment (variant of `||=`), meaning `a.b ? a.b = c`.
- `a.b? = c` is a soak assignment, meaning `a.b = c if c?`.
  - May be a little confusing in this form since the `?` works on the opposite side, but makes sense when you consider parameter and/or destructuring (e.g. `([a, b]?) ->`).
- The arity of `?` depends on the space before it. Binary when spaced, unary otherwise. This rule hasn't changed from CoffeeScript.
- The space between `?` and `=` doesn't matter.
- `c = a.b?` is just a normal assignment of the result of an existence check.

**Comment by scribu** [comment]
Right, so that clears up the existential operator. Thanks.

How about `a =? b` instead? It's a lot clearer, IMO.

`([a, b]?) ->` wouldn't work anymore, but you could write `(arg) -> [a, b] =? arg`.

**Comment by satyr** [comment]
> How about `a =? b` instead?
> `([a, b]?) ->` wouldn't work anymore

No go, since this syntax is added mainly for parameter/destructuring.

**Comment by scribu** [comment]
Ok, could you give an example of an actual function that would make good use of conditional destructuring of a parameter?

Also, how about having `([a, b]?) ->` as well as `a =? b` ?

**Comment by satyr** [comment]
> an example of an actual function that would make good use of conditional destructuring of a parameter?

https://github.com/satyr/coco/blob/0.6.1/Cokefile#L175 is one for destructuring.
I don't think there are parameters that use it in Coco source yet, but the benefit is obvious as patterns like below is fairly common:

```
({ok, ng}?) -> ...

# instead of:
(callbacks) ->
  {ok, ng} = callbacks if callbacks?
  ...
```

> Also, how about having `([a, b]?) ->` as well as `a =? b` ?

Another syntax with the same semantics? Pointless I think.

**Comment by scribu** [comment]
> https://github.com/satyr/coco/blob/0.6.1/Cokefile#L175 is one for destructuring.

Sure, which could be handled with `=?`.

> I don't think there are parameters that use it in Coco source yet, but the benefit is obvious as patterns like below is fairly common:

`({ok, ng}?) -> ...`

I disagree. It's uncommon to _optionally_ accept an object as a parameter and then destructure it.

You would instead use a placeholder object:

`({a, b} = {a: 'foo'}) -> ...`

**Comment by satyr** [comment]
Also see [the original thread](http://groups.google.com/group/coffeescript/browse_thread/thread/27375290f34c2129/14573f215ef497e3) of the syntax idea.

**Comment by satyr** [comment]
In a way, soak access and soak assign are two sides of the same coin.
- `z = that if a?0?1?2`
- `[, [,, [z]?]?]? = a`

Anyway, closing as the answer seems to be accepted.
