### ISSUE TITLE
Deprecate `function ->`

### ISSUE THREAD

**Issue by satyr** [satyr/coco#83]
- `function then` is nicer.
- `function ~>` can be `~function then`.
- Consistent with the `let ->` → `let then` change.

**Comment by ceymard** [comment]
I kind of liked the arrows.

I hope you don't want to remove them at all ?

Plus, `then` has a very conditional meaning, not very suited for this kind of declaration.

I actually find writing `function then`, or `for then` awkward (`then` being really associated with `if`)

**Comment by satyr** [comment]
> I hope you don't want to remove them at all ?

The normal function syntax will stay. This issue is about removing this syntax:

```
function f (...) ->
  ...
```

in favor of:

```
function f ...
  ...
```

> `then` has a very conditional meaning, not very suited for this kind of declaration

`then` means "start implicit block here" in Co{co,ffeeScript}. You can use it everywhere that requires a block, and it is handier to say `if then` than `if <INDENT>` or something.

**Comment by ceymard** [comment]
Do you mean this will be valid :

```
function fun a, b
    stuff
```

**Comment by satyr** [comment]
> ```
> function fun a, b
>     stuff
> ```

Valid already. Supported around 0.5.2 I think.

**Comment by ceymard** [comment]
What about class constructors ?

So far we have to write

```
class
    -> ...
```

Will we also be able to write

```
class
   function
       ...
```

**Comment by satyr** [comment]
I guess that has to stay.
- We need to distinguish constructor from local functions.
- Constructor is named already. No need for `function` there.

**Comment by ceymard** [comment]
no more objections here.

**Comment by ceymard** [comment]
Ah just one thing though :

```
f = function a, b
    ...
```

does not compile.
whereas

```
function f a, b
   ...
```

does.

I suppose this should be fixed.

**Comment by satyr** [comment]
`function a b` is the same as `function a(b)`. You write `function (a, b)` if you want `a` to be an argument.

**Comment by ceymard** [comment]
Alright, just got why it would be a problem.

**Comment by ceymard** [comment]
Another thing

"label: function" does not compile, whereas "label: ->" does. Is it expected ?

**Comment by satyr** [comment]
The block is required for `function`--that has to be `label: function then`. Same for `class`/`let` etc.

```
$ coco -bpe 'let'
Error: Parse error on line 1: Unexpected 'TERMINATOR'

$ coco -bpe 'let then'
(function(){}.call(this));
```
