### ISSUE TITLE
Proposal: Object declaration in assignments defaults

### ISSUE THREAD

**Issue by ceymard** [satyr/coco#84]
Proposing this :

```
({ @toto = 3, baz }, a = 5) ->
```

would give :

```
(_arg, a) ->
    a = if a is undefined then 5 else a
    @toto = if _arg.toto is undefined then 3 else _arg.toto
    baz = _arg.baz
```

It would also be nice to be able to name the object arguments with other names than `_arg` `_arg2` ...

**Comment by satyr** [comment]
Object destructuring you mean? We got it already:

```
$ coco -bpe '({@todo ? 3}) ->'
(function(_arg){
  var _ref;
  this.todo = (_ref = _arg.todo) != null ? _ref : 3;
});
```

> It would also be nice to be able to name the object arguments with other names than `_arg` `_arg2`

Agreed. Syntax suggestions?

**Comment by ceymard** [comment]
We really need to document stuff :) -- didn't have much time lately, but really planning on it.

The problem with adding a syntax is that it's fairly hard to not interfere with current constructs.

Suggestions :
1) `({ foo } : baz) ->` kinda awkward, but has a feeling of naming since : generally is used with labels, and it shouldn't clash with object definition.
2) `(baz ! { foo }) ->` hmm :-|
3) `(baz@{ foo }) ->` @ is already used for `this`
4) `(baz / { foo }) ->` ..

The problem I have with them is that none are really clear, and most of them have meaning in other contexts (except for 1).

**Comment by satyr** [comment]
> We really need to document stuff :) -- didn't have much time lately, but really planning on it.

It's in the _additions_ page, but looks like the page has become too big to skim through.

**Comment by ceymard** [comment]
Yes, by documentation I meant a guide so that new users can have their hands on coco pretty fast.

**Comment by satyr** [comment]
> 1) `({ foo } : baz) ->` kinda awkward, but has a feeling of naming since : generally is used with labels, and it shouldn't clash with object definition.

This may actually work. Can you rename the issue title or open another issue for that?
