### ISSUE TITLE
Inconsistancy/Unintuitive stuff: attribute after function calling doesn't work with numbers

### ISSUE THREAD

**Issue by ceymard** [satyr/coco#87]
`foo bar .baz` -> `foo(bar).baz;`

NOT A BUG (but feels weird) :

`foo bar .0` -> `foo(bar(.0));`

Expected :

``` javascript
foo(bar)[0];
```

**Comment by satyr** [comment]
I wouldn't call it a bug; `.0` is primary a number literal.
- `f .0` => `f(0.0)`

The exception is when it's placed immediately after an accessible token, where it's treated as `.` and `0`.
- `a.0` => `a. 0` => `a[0]`

**Comment by ceymard** [comment]
Ah, right.

Although, if we are in a grammar where .[0-9] is allowed, then why allow the ambiguity of it being also used as a number literal ?

I am all in favor of removing the `.0` for number literal, as using it as index is more elegant.

I already have written several thousand lines of coco ; I never have used more than a couple float numbers but I have used indexing in a lot of places.

I do not mind having to write `0.0` occasionally if it means I get indexing everywhere.

**Comment by satyr** [comment]
> Although, if we are in a grammar where .[0-9] is allowed, then why allow the ambiguity of it being also used as a number literal ?

Only due to compatibility--we inherited it from Coffee. Indexing by dot-number became available later.

> I am all in favor of removing the `.0` for number literal

That's a possibility. Coffee didn't inherit `0.` from JS after all.

**Comment by satyr** [comment]
Two problems:
- Backward compability.
- Need for a new hack to parse `a.0.1` as `a[0][1]`. The current way:
  - relies on dot-leading numbers being valid; the split happens after we lex them naturally:
    - `a.0.1` => `a .0 .1` => `a . 0 . 1`
  - won't work if we invalidate them:
    - `a.0.1` => `a . 0.1` => ??

**Comment by ceymard** [comment]
Maybe by upping the priority of the `.` operator over float number priority ?

That way `a.0.1` => `a[0].1` => `a[0][1]` ?

**Comment by satyr** [comment]
Yes, disallowing float number with dot after dot/ADI may work.

**Comment by satyr** [comment]
Seems to work. I'll merge it on 0.6.2 unless anyone has objections.

**Comment by ceymard** [comment]
Perfect.
