### ISSUE TITLE
instanceof not working properly

### ISSUE THREAD

**Issue by kennyb** [satyr/coco#89]
in coffee this code neither works. it's not super high priority... I just wrote a workaround function :)

```
class Foo
    ->

class Bar extends Foo
    ->

console.log Bar instanceof Foo
```

**Comment by satyr** [comment]
That's working correctly--`Bar` isn't an _instance of_ `Foo`.

```
$ coco -se
  class Foo then
  class Bar extends Foo then

  * Bar instanceof Foo
    new Bar instanceof Foo
    Bar.superclass is Foo

[ false, true, true ]
```

**Comment by ghost** [comment]
`Bar` is actually a constructor function, so it shouldn't be an instance of `Foo`...try `Bar instanceof Function`, `Bar.prototype instanceof Foo`, and `new Bar instanceof Foo`.

**Edit**: Mid-air collision with @satyr.
