### ISSUE TITLE
piping

### ISSUE THREAD

**Issue by satyr** [satyr/coco#90]
Random idea on the Unix-pipe-like construction some people seem enthusiastic about:

```
X => Y => Z
```

↓

```
(_ = X; _ = Y; Z)
```

e.g. `g(f(a) + b) * c` → `f a => g _ + b => _ * c`

**Comment by dsc** [comment]
What was the rationale for choosing `_`? Most of my files start with:

``` coffee
_ = require 'underscore'
```

What does the result get bound to in this case? A newly local `_`? Does it override `_`? Does it inject a new variable (maybe `__` or `_1`)?

**Comment by satyr** [comment]
> What was the rationale for choosing `_`?

Usability. Probably the same rationale that _underscore_ chose `_` with.

> ```
> `_ = require 'underscore'`
> ```
> 
> What does the result get bound to in this case?

`_`. Nothing prevents you to use context-created variables (`it` and `that` are others) out of the context, but you should be aware that it can get re-assigned.

See #54 for a related discussion.
