### ISSUE TITLE
Skip temporary variable in loops

### ISSUE THREAD

**Issue by scribu** [satyr/coco#92]
`myVar = (i for i from 1 to 5)`

generates:

```
var i, myVar, _res;
_res = [];
for (i = 1; i <= 5; ++i) {
  _res.push(i);
}
myVar = _res;
```

Would it be possible to use `myVar` directly? It would help debugging a lot.

Of course, _res should still be used when it's assigned to an object propery like `window.myVar` or even `@myVar`.

**Comment by satyr** [comment]
The `_res` case is only an optimization over the generic IIFE compilation (e.g. `r = try f!`). The both have to behave the same.

Say, mapping `ns` to itself:

```
ns = (n+1 for n of ns)
```

wouldn't work if `ns` were used to store the results:

```
var ns, n, _i, _ref, _len;
ns = [];
for (_i = 0, _len = ns.length; _i < _len; ++_i) {
  n = _ref[_i];
  ns.push(n + 1);
}
```

> It would help debugging a lot

How?

**Comment by scribu** [comment]
> Say, mapping ns to itself: `ns = (n+1 for n of ns)`

Didn't think of that case.

You're right, it's not worth it.
