### ISSUE TITLE
Scope Introduction with Implicit Argument

### ISSUE THREAD

**Issue by dsc** [satyr/coco#94]
I often find myself writing code like:

``` coffee
cats = @categories or @lookup 'categories', []
cats = cats.split(/,\s*/) if typeof cats is 'string'
@categories = cats.map Category.instanceById
```

This could be radically simplified. Unfortunately, it is not handled by `with` or `let` syntax, as neither implicitly create a variable for all these assignments (especially the conditional one). Assigning to `this` is illegal, so `with` is useless for anything immutable (strings, numbers, dates, etc).

I propose the following:

``` coffee
@categories = let @categories or @lookup 'categories', []
    it.split(/,\s*/) if typeof it is 'string'
    it.map Category.instanceById
```

This sugar would capture the expression as the implicit variable `it`, and assign to it for every line in the block that does not, itself, perform an assignment. The last line would, as always, yield its value, which in this case, will always be `it`.

Syntactically, `let` requires an assignment, whereas this extension does not. This allows us to disambiguate the two.

I know I'd find this substantially more useful than the current syntax for `let` or `with`.

ps. It's sad that github-flavored-markdown recognizes four-ticks+`coffee` but not `coco` for source-blocks.

**Comment by dsc** [comment]
I plan to implement this in my branch either way, but I figured I'll mention it here before I do so as I won't get to it until the weekend.

**Comment by satyr** [comment]
> and assign to it for every line in the block that does not, itself, perform an assignment

You mean, implicit `it =` on each line? Then I think the second line of your example needs to be

```
  if typeof it is 'string' then it.split(/,\s*/) else it
```

Seems to me the same can achieved with `let` as it is

```
@categories = let it = @categories or @lookup \categories []
  it.=split /,\s*/ if typeof it is \string
  it.map Category.instanceById
```

or with the new `=>` operator:

```
@categories or @lookup \categories []
=> (if typeof _ is \string then _.split /,\s*/ else _)
=> @categories = _.map Category.instanceById
```

**Comment by dsc** [comment]
I actually wasn't aware of the `=>` operator. I'll consider the user-cases and get back to you.
