### ISSUE TITLE
docs for bound classes

### ISSUE THREAD

**Issue by kennyb** [satyr/coco#95]
should be on the constructor like this...

```
class Bound
  (i) ~>
    @i = i
```

**Comment by satyr** [comment]
?

**Comment by scribu** [comment]
There is no such thing as a bound class. There's only the `~>` operator, which maps `this` to the outer scope and is already documented.

**Comment by scribu** [comment]
Actually, using the `~>` operator on the constructor makes no sense. So, to quote satyr:

?

**Comment by satyr** [comment]
> There is no such thing as a bound class

Class constructors can be bound. See the `class` section in the additions page.

**Comment by scribu** [comment]
Right, so writing `class Bound (@i) ~>` is equivalent to `Bound = class then (@i) ~>`

But what are bound classes good for?

**Comment by scribu** [comment]
Nevermind, found it:

`can be bound using ~> to be new-free, like native Array which works with or without new.`

**Comment by kennyb** [comment]
right, but the demonstrated code won't work...

```
Bound = class then ~>
  (i) ->
    @i = i
```

this won't produce the same output...

**Comment by satyr** [comment]
Right.

#### Pros
- Can be used without `new`.
- Can be used with splat: `Bound ...args`

#### Cons
- `super` doesn't work from subclass constructors.

**Comment by satyr** [comment]
> ```
> Bound = class then ~>
>   (i) ->
>     @i = i
> ```
> 
> this won't produce the same output...

Nope, that's mal-written. Remember that `then` is a keyword that starts single-line block (same as CoffeeScript). Hence the example is short for:

```
class Bound
  ~>
```

**Comment by kennyb** [comment]
oh, I see... then, it was a bit unclear to me how to convert an existing class to be bound :) - neither did it mention that the constructor arrow should be modified...

edit: I mean, it is my mistake, but others may get caught up there too

**Comment by satyr** [comment]
> others may get caught up there too

Maybe. Feel free to edit away any such ambiguities, quirks etc. on the wiki.
