### ISSUE TITLE
Inconsistent behaviour of the `?` operator when using the `.` operator

### ISSUE THREAD

**Issue by ceymard** [satyr/coco#98]
`a = b ? c` -> `a = typeof b != 'undefined' && b !== null ? b : c;`, this is correct.

`a = b.a ? c` -> `a = (_ref = a.b) != null ? _ref : c;`

expected `a = typeof (_ref = a.b) != 'undefined' && _ref !== null ? _ref : c;`

**Comment by satyr** [comment]
It's an optimized compilation.
- `x != null` is identical to `x !== void 7 && x !== null`.
- `b` needs `typeof` check to avoid reference error. `b.a` doesn't.
